import 'historical_baseline_provider.dart';

class HistoricalDataLab6 {
  static const List<HistoricalRecord> lab6Data = [
    // ═══════════════════════════════════════════════════════════════════════════
    // MONITORS (Merged from previous baseline)
    // ═══════════════════════════════════════════════════════════════════════════
    HistoricalRecord(
      deskId: 'LAB6 - PC1',
      category: 'MONITOR',
      brand: 'ACER',
      mfgSerial: '253Q02129',
      dntsSerial: 'L6-MR-02',
      dateAcquired: 'August 2, 2025',
      notes: 'FUNCTIONAL',
    ),
    HistoricalRecord(
      deskId: 'LAB6 - PC2',
      category: 'MONITOR',
      brand: 'ACER',
      mfgSerial: '252401944',
      dntsSerial: 'L6-MR-03',
      dateAcquired: 'August 2, 2025',
      notes: 'FUNCTIONAL',
    ),
    HistoricalRecord(
      deskId: 'LAB6 - PC3',
      category: 'MONITOR',
      brand: 'ACER',
      mfgSerial: '253R17573',
      dntsSerial: 'L6-MR-03',
      dateAcquired: 'August 2, 2025',
      notes: 'FUNCTIONAL',
    ),
    HistoricalRecord(
      deskId: 'LAB6 - PC4',
      category: 'MONITOR',
      brand: 'ACER',
      mfgSerial: '253R16416',
      dntsSerial: 'L6-MR-04',
      dateAcquired: 'August 2, 2025',
      notes: 'FUNCTIONAL',
    ),
    HistoricalRecord(
      deskId: 'LAB6 - PC5',
      category: 'MONITOR',
      brand: 'ACER',
      mfgSerial: '253R17617',
      dntsSerial: 'L6-MR-05',
      dateAcquired: 'August 2, 2025',
      notes: 'FUNCTIONAL',
    ),
    HistoricalRecord(
      deskId: 'LAB6 - PC6',
      category: 'MONITOR',
      brand: 'ACER',
      mfgSerial: '252401320',
      dntsSerial: 'L6-MR-06',
      dateAcquired: 'August 2, 2025',
      notes: 'FUNCTIONAL',
    ),
    HistoricalRecord(
      deskId: 'LAB6 - PC7',
      category: 'MONITOR',
      brand: 'ACER',
      mfgSerial: '253Q01827',
      dntsSerial: 'L6-MR-07',
      dateAcquired: 'August 2, 2025',
      notes: 'FUNCTIONAL',
    ),
    HistoricalRecord(
      deskId: 'LAB6 - PC8',
      category: 'MONITOR',
      brand: 'ACER',
      mfgSerial: '253R174563',
      dntsSerial: 'L6-MR-08',
      dateAcquired: 'August 2, 2025',
      notes: 'FUNCTIONAL',
    ),
    HistoricalRecord(
      deskId: 'LAB6 - PC9',
      category: 'MONITOR',
      brand: 'ACER',
      mfgSerial: '253R17430',
      dntsSerial: 'L6-MR-09',
      dateAcquired: 'August 2, 2025',
      notes: 'FUNCTIONAL',
    ),
    HistoricalRecord(
      deskId: 'LAB6 - PC10',
      category: 'MONITOR',
      brand: 'ACER',
      mfgSerial: '253R17429',
      dntsSerial: 'L6-MR-10',
      dateAcquired: 'August 2, 2025',
      notes: 'FUNCTIONAL',
    ),
    HistoricalRecord(
      deskId: 'LAB6 - PC11',
      category: 'MONITOR',
      brand: 'ACER',
      mfgSerial: '252401293',
      dntsSerial: 'L6-MR-11',
      dateAcquired: 'August 2, 2025',
      notes: 'FUNCTIONAL',
    ),
    HistoricalRecord(
      deskId: 'LAB6 - PC12',
      category: 'MONITOR',
      brand: 'ACER',
      mfgSerial: '253Q01823',
      dntsSerial: 'L6-MR-12',
      dateAcquired: 'August 2, 2025',
      notes: 'FUNCTIONAL',
    ),
    HistoricalRecord(
      deskId: 'LAB6 - PC13',
      category: 'MONITOR',
      brand: 'ACER',
      mfgSerial: '253R17121',
      dntsSerial: 'L6-MR-13',
      dateAcquired: 'August 2, 2025',
      notes: 'FUNCTIONAL',
    ),
    HistoricalRecord(
      deskId: 'LAB6 - PC14',
      category: 'MONITOR',
      brand: 'ACER',
      mfgSerial: '252401091',
      dntsSerial: 'L6-MR-14',
      dateAcquired: 'August 2, 2025',
      notes: 'FUNCTIONAL',
    ),
    HistoricalRecord(
      deskId: 'LAB6 - PC15',
      category: 'MONITOR',
      brand: 'ACER',
      mfgSerial: '253R17642',
      dntsSerial: 'L6-MR-15',
      dateAcquired: 'August 2, 2025',
      notes: 'FUNCTIONAL',
    ),
    HistoricalRecord(
      deskId: 'LAB6 - PC16',
      category: 'MONITOR',
      brand: 'ACER',
      mfgSerial: '253Q01826',
      dntsSerial: 'L6-MR-16',
      dateAcquired: 'August 2, 2025',
      notes: 'FUNCTIONAL',
    ),
    HistoricalRecord(
      deskId: 'LAB6 - PC17',
      category: 'MONITOR',
      brand: 'ACER',
      mfgSerial: '252401962',
      dntsSerial: 'L6-MR-17',
      dateAcquired: 'August 2, 2025',
      notes: 'FUNCTIONAL',
    ),
    HistoricalRecord(
      deskId: 'LAB6 - PC18',
      category: 'MONITOR',
      brand: 'ACER',
      mfgSerial: '253R17624',
      dntsSerial: 'L6-MR-18',
      dateAcquired: 'August 2, 2025',
      notes: 'FUNCTIONAL',
    ),
    HistoricalRecord(
      deskId: 'LAB6 - PC19',
      category: 'MONITOR',
      brand: 'ACER',
      mfgSerial: '253R17555',
      dntsSerial: 'L6-MR-19',
      dateAcquired: 'August 2, 2025',
      notes: 'FUNCTIONAL',
    ),
    HistoricalRecord(
      deskId: 'LAB6 - PC20',
      category: 'MONITOR',
      brand: 'ACER',
      mfgSerial: '253R17595',
      dntsSerial: 'L6-MR-20',
      dateAcquired: 'August 2, 2025',
      notes: 'FUNCTIONAL',
    ),
    HistoricalRecord(
      deskId: 'LAB6 - PC21',
      category: 'MONITOR',
      brand: 'ACER',
      mfgSerial: '252401083',
      dntsSerial: 'L6-MR-21',
      dateAcquired: 'August 2, 2025',
      notes: 'FUNCTIONAL',
    ),
    HistoricalRecord(
      deskId: 'LAB6 - PC22',
      category: 'MONITOR',
      brand: 'ACER',
      mfgSerial: '253R17541',
      dntsSerial: 'L6-MR-22',
      dateAcquired: 'August 2, 2025',
      notes: 'FUNCTIONAL',
    ),
    HistoricalRecord(
      deskId: 'LAB6 - PC23',
      category: 'MONITOR',
      brand: 'ACER',
      mfgSerial: '253Q01863',
      dntsSerial: 'L6-MR-23',
      dateAcquired: 'August 2, 2025',
      notes: 'FUNCTIONAL',
    ),
    HistoricalRecord(
      deskId: 'LAB6 - PC24',
      category: 'MONITOR',
      brand: 'ACER',
      mfgSerial: '253R17110',
      dntsSerial: 'L6-MR-24',
      dateAcquired: 'August 2, 2025',
      notes: 'FUNCTIONAL',
    ),
    HistoricalRecord(
      deskId: 'LAB6 - PC25',
      category: 'MONITOR',
      brand: 'ACER',
      mfgSerial: '253R17510',
      dntsSerial: 'L6-MR-24',
      dateAcquired: 'August 2, 2025',
      notes: 'FUNCTIONAL',
    ),
    HistoricalRecord(
      deskId: 'LAB6 - PC26',
      category: 'MONITOR',
      brand: 'ACER',
      mfgSerial: '253R17645',
      dntsSerial: 'L6-MR-26',
      dateAcquired: 'August 2, 2025',
      notes: 'FUNCTIONAL',
    ),
    HistoricalRecord(
      deskId: 'LAB6 - PC27',
      category: 'MONITOR',
      brand: 'ACER',
      mfgSerial: '253Q02158',
      dntsSerial: 'L6-MR-27',
      dateAcquired: 'August 2, 2025',
      notes: 'FUNCTIONAL',
    ),
    HistoricalRecord(
      deskId: 'LAB6 - PC28',
      category: 'MONITOR',
      brand: 'ACER',
      mfgSerial: '253R17124',
      dntsSerial: 'L6-MR-28',
      dateAcquired: 'August 2, 2025',
      notes: 'FUNCTIONAL',
    ),
    HistoricalRecord(
      deskId: 'LAB6 - PC29',
      category: 'MONITOR',
      brand: 'ACER',
      mfgSerial: '253R17569',
      dntsSerial: 'L6-MR-29',
      dateAcquired: 'August 2, 2025',
      notes: 'FUNCTIONAL',
    ),
    HistoricalRecord(
      deskId: 'LAB6 - PC30',
      category: 'MONITOR',
      brand: 'ACER',
      mfgSerial: '253R17406',
      dntsSerial: 'L6-MR-30',
      dateAcquired: 'August 2, 2025',
      notes: 'FUNCTIONAL',
    ),
    HistoricalRecord(
      deskId: 'LAB6 - PC31',
      category: 'MONITOR',
      brand: 'ACER',
      mfgSerial: '252401956',
      dntsSerial: 'L6-MR-31',
      dateAcquired: 'August 2, 2025',
      notes: 'FUNCTIONAL',
    ),
    HistoricalRecord(
      deskId: 'LAB6 - PC32',
      category: 'MONITOR',
      brand: 'ACER',
      mfgSerial: '253R17533',
      dntsSerial: 'L6-MR-32',
      dateAcquired: 'August 2, 2025',
      notes: 'FUNCTIONAL',
    ),
    HistoricalRecord(
      deskId: 'LAB6 - PC33',
      category: 'MONITOR',
      brand: 'ACER',
      mfgSerial: '253R17567',
      dntsSerial: 'L6-MR-33',
      dateAcquired: 'August 2, 2025',
      notes: 'FUNCTIONAL',
    ),
    HistoricalRecord(
      deskId: 'LAB6 - PC34',
      category: 'MONITOR',
      brand: 'ACER',
      mfgSerial: '253Q02056',
      dntsSerial: 'L6-MR-34',
      dateAcquired: 'August 2, 2025',
      notes: 'FUNCTIONAL',
    ),
    HistoricalRecord(
      deskId: 'LAB6 - PC35',
      category: 'MONITOR',
      brand: 'ACER',
      mfgSerial: '253R17517',
      dntsSerial: 'L6-MR-35',
      dateAcquired: 'August 2, 2025',
      notes: 'FUNCTIONAL',
    ),
    HistoricalRecord(
      deskId: 'LAB6 - PC36',
      category: 'MONITOR',
      brand: 'ACER',
      mfgSerial: '253R17448',
      dntsSerial: 'L6-MR-36',
      dateAcquired: 'August 2, 2025',
      notes: 'FUNCTIONAL',
    ),
    HistoricalRecord(
      deskId: 'LAB6 - PC37',
      category: 'MONITOR',
      brand: 'ACER',
      mfgSerial: '252401282',
      dntsSerial: 'L6-MR-37',
      dateAcquired: 'August 2, 2025',
      notes: 'FUNCTIONAL',
    ),
    HistoricalRecord(
      deskId: 'LAB6 - PC38',
      category: 'MONITOR',
      brand: 'ACER',
      mfgSerial: '252401230',
      dntsSerial: 'L6-MR-38',
      dateAcquired: 'August 2, 2025',
      notes: 'FUNCTIONAL',
    ),
    HistoricalRecord(
      deskId: 'LAB6 - PC39',
      category: 'MONITOR',
      brand: 'ACER',
      mfgSerial: '252400397',
      dntsSerial: 'L6-MR-39',
      dateAcquired: 'August 2, 2025',
      notes: 'FUNCTIONAL',
    ),
    HistoricalRecord(
      deskId: 'LAB6 - PC40',
      category: 'MONITOR',
      brand: 'ACER',
      mfgSerial: '253R17605',
      dntsSerial: 'L6-MR-40',
      dateAcquired: 'August 2, 2025',
      notes: 'FUNCTIONAL',
    ),
    HistoricalRecord(
      deskId: 'LAB6 - PC41',
      category: 'MONITOR',
      brand: 'ACER',
      mfgSerial: '252400374',
      dntsSerial: 'L6-MR-41',
      dateAcquired: 'August 2, 2025',
      notes: 'FUNCTIONAL',
    ),
    HistoricalRecord(
      deskId: 'LAB6 - PC42',
      category: 'MONITOR',
      brand: 'SAMSUNG',
      mfgSerial: 'MRCQHYCDB00196M',
      dntsSerial: 'L6-MR-42',
      dateAcquired: 'MARCH 1, 2018',
      notes: 'EXIBIT ROOM - FUNCTIONAL',
    ),
    HistoricalRecord(
      deskId: 'LAB6 - PC43',
      category: 'MONITOR',
      brand: 'SAMSUNG',
      mfgSerial: 'MRCQHYCDA03451Y',
      dntsSerial: 'L6-MR-43',
      dateAcquired: 'MARCH 1, 2018',
      notes: 'EXIBIT ROOM - FUNCTIONAL',
    ),
    HistoricalRecord(
      deskId: 'LAB6 - PC44',
      category: 'MONITOR',
      brand: 'SAMSUNG',
      mfgSerial: 'MRCQHYCDA03141F',
      dntsSerial: 'L6-MR-44',
      dateAcquired: 'MARCH 1, 2018',
      notes: 'EXIBIT ROOM - FUNCTIONAL',
    ),
    HistoricalRecord(
      deskId: 'LAB6 - PC45',
      category: 'MONITOR',
      brand: 'SAMSUNG',
      mfgSerial: 'MRCQHYCDB00171R',
      dntsSerial: 'L6-MR-45',
      dateAcquired: 'MARCH 1, 2018',
      notes: 'EXIBIT ROOM - FUNCTIONAL',
    ),
    HistoricalRecord(
      deskId: 'LAB6 - PC46',
      category: 'MONITOR',
      brand: 'SAMSUNG',
      mfgSerial: 'MRCQHYCD901097Z',
      dntsSerial: 'L6-MR-46',
      dateAcquired: 'MARCH 1, 2018',
      notes: 'EXIBIT ROOM - FUNCTIONAL',
    ),
    HistoricalRecord(
      deskId: 'LAB6 - PC47',
      category: 'MONITOR',
      brand: 'SAMSUNG',
      mfgSerial: 'MRCQHYCDA03306T',
      dntsSerial: 'LAB5-MR-46',
      dateAcquired: 'MARCH 1, 2018',
      notes: 'ID PROCESSING / PIT-OS - FUNCTIONAL',
    ),
    HistoricalRecord(
      deskId: 'LAB6 - PC48',
      category: 'MONITOR',
      brand: 'SAMSUNG',
      mfgSerial: 'MRCQHYCDA03424F',
      dntsSerial: 'LAB 5-MR-31',
      dateAcquired: 'MARCH 1, 2018',
      notes: 'ACCOUNTING - FUNCTIONAL',
    ),

    // ═══════════════════════════════════════════════════════════════════════════
    // SYSTEM UNITS
    // ═══════════════════════════════════════════════════════════════════════════
    HistoricalRecord(deskId: 'LAB6 - PC1', category: 'SYSTEM UNIT', brand: 'ACER', mfgSerial: 'DTVPUSPO63734057789600', dntsSerial: 'L6 SU-1', dateAcquired: 'MARCH 1, 2018', notes: 'Intel i3 - FUNCTIONAL'),
    HistoricalRecord(deskId: 'LAB6 - PC2', category: 'SYSTEM UNIT', brand: 'ACER', mfgSerial: 'DTVPUSPO637340577A9600', dntsSerial: 'L6 SU-2', dateAcquired: 'MARCH 1, 2018', notes: 'Intel i3 - FUNCTIONAL'),
    HistoricalRecord(deskId: 'LAB6 - PC3', category: 'SYSTEM UNIT', brand: 'ACER', mfgSerial: 'DTVPUSPO63734057939600', dntsSerial: 'L6 SU-3', dateAcquired: 'MARCH 1, 2018', notes: 'Intel i3 - FUNCTIONAL'),
    HistoricalRecord(deskId: 'LAB6 - PC4', category: 'SYSTEM UNIT', brand: 'ACER', mfgSerial: 'DTVPUSPO637340577C9600', dntsSerial: 'L6 SU-4', dateAcquired: 'MARCH 1, 2018', notes: 'Intel i3 - FUNCTIONAL'),
    HistoricalRecord(deskId: 'LAB6 - PC5', category: 'SYSTEM UNIT', brand: 'ACER', mfgSerial: 'DTVPUSPO63734057929600', dntsSerial: 'L6 SU-5', dateAcquired: 'MARCH 1, 2018', notes: 'Intel i3 - FUNCTIONAL'),
    HistoricalRecord(deskId: 'LAB6 - PC6', category: 'SYSTEM UNIT', brand: 'ACER', mfgSerial: 'DTVPUSPO63734057859600', dntsSerial: 'L6 SU-6', dateAcquired: 'MARCH 1, 2018', notes: 'Intel i3 - FUNCTIONAL'),
    HistoricalRecord(deskId: 'LAB6 - PC7', category: 'SYSTEM UNIT', brand: 'ACER', mfgSerial: 'DTVPUSPO63734057919600', dntsSerial: 'L6 SU-7', dateAcquired: 'MARCH 1, 2018', notes: 'Intel i3 - FUNCTIONAL'),
    HistoricalRecord(deskId: 'LAB6 - PC8', category: 'SYSTEM UNIT', brand: 'ACER', mfgSerial: 'DTVPUSPO637340577D9600', dntsSerial: 'L6 SU-8', dateAcquired: 'MARCH 1, 2018', notes: 'Intel i3 - FUNCTIONAL'),
    HistoricalRecord(deskId: 'LAB6 - PC9', category: 'SYSTEM UNIT', brand: 'ACER', mfgSerial: 'DTVPUSPO63734057849600', dntsSerial: 'L6 SU-9', dateAcquired: 'MARCH 1, 2018', notes: 'Intel i3 - FUNCTIONAL'),
    HistoricalRecord(deskId: 'LAB6 - PC10', category: 'SYSTEM UNIT', brand: 'ACER', mfgSerial: 'DTVPUSPO63734057879600', dntsSerial: 'L6 SU-10', dateAcquired: 'MARCH 1, 2018', notes: 'Intel i3 - FUNCTIONAL'),
    HistoricalRecord(deskId: 'LAB6 - PC11', category: 'SYSTEM UNIT', brand: 'ACER', mfgSerial: 'DTVPUSPO637340576E9600', dntsSerial: 'L6 SU-11', dateAcquired: 'MARCH 1, 2018', notes: 'Intel i3 - FUNCTIONAL'),
    HistoricalRecord(deskId: 'LAB6 - PC12', category: 'SYSTEM UNIT', brand: 'ACER', mfgSerial: 'DTVPUSPO637340578D9600', dntsSerial: 'L6 SU-12', dateAcquired: 'MARCH 1, 2018', notes: 'Intel i3 - FUNCTIONAL'),
    HistoricalRecord(deskId: 'LAB6 - PC13', category: 'SYSTEM UNIT', brand: 'ACER', mfgSerial: 'DTVPUSPO637340577F9600', dntsSerial: 'L6 SU-13', dateAcquired: 'MARCH 1, 2018', notes: 'Intel i3 - FUNCTIONAL'),
    HistoricalRecord(deskId: 'LAB6 - PC14', category: 'SYSTEM UNIT', brand: 'ACER', mfgSerial: 'DTVPUSPO63734057749600', dntsSerial: 'L6 SU-14', dateAcquired: 'MARCH 1, 2018', notes: 'Intel i3 - FUNCTIONAL'),
    HistoricalRecord(deskId: 'LAB6 - PC15', category: 'SYSTEM UNIT', brand: 'ACER', mfgSerial: 'DTVPUSPO637340577B9600', dntsSerial: 'L6 SU-15', dateAcquired: 'MARCH 1, 2018', notes: 'Intel i3 - FUNCTIONAL'),
    HistoricalRecord(deskId: 'LAB6 - PC16', category: 'SYSTEM UNIT', brand: 'ACER', mfgSerial: 'DTVPUSPO637340576C9600', dntsSerial: 'L6 SU-16', dateAcquired: 'MARCH 1, 2018', notes: 'Intel i3 - FUNCTIONAL'),
    HistoricalRecord(deskId: 'LAB6 - PC17', category: 'SYSTEM UNIT', brand: 'ACER', mfgSerial: 'DTVPUSPO63734057729600', dntsSerial: 'L6 SU-17', dateAcquired: 'MARCH 1, 2018', notes: 'Intel i3 - FUNCTIONAL'),
    HistoricalRecord(deskId: 'LAB6 - PC18', category: 'SYSTEM UNIT', brand: 'ACER', mfgSerial: 'DTVPUSPO63734057909600', dntsSerial: 'L6 SU-18', dateAcquired: 'MARCH 1, 2018', notes: 'Intel i3 - FUNCTIONAL'),
    HistoricalRecord(deskId: 'LAB6 - PC19', category: 'SYSTEM UNIT', brand: 'ACER', mfgSerial: 'DTVPUSPO63734057779600', dntsSerial: 'L6 SU-19', dateAcquired: 'MARCH 1, 2018', notes: 'Intel i3 - FUNCTIONAL'),
    HistoricalRecord(deskId: 'LAB6 - PC20', category: 'SYSTEM UNIT', brand: 'ACER', mfgSerial: 'DTVPUSPO63734057799600', dntsSerial: 'L6 SU-20', dateAcquired: 'MARCH 1, 2018', notes: 'Intel i3 - FUNCTIONAL'),
    HistoricalRecord(deskId: 'LAB6 - PC21', category: 'SYSTEM UNIT', brand: 'ACER', mfgSerial: 'DTVPUSPO63734057819600', dntsSerial: 'L6 SU-21', dateAcquired: 'MARCH 1, 2018', notes: 'Intel i3 - FUNCTIONAL'),
    HistoricalRecord(deskId: 'LAB6 - PC22', category: 'SYSTEM UNIT', brand: 'ACER', mfgSerial: 'DTVPUSPO63734057809600', dntsSerial: 'L6 SU-22', dateAcquired: 'MARCH 1, 2018', notes: 'Intel i3 - FUNCTIONAL'),
    HistoricalRecord(deskId: 'LAB6 - PC23', category: 'SYSTEM UNIT', brand: 'ACER', mfgSerial: 'DTVPUSPO63734057839600', dntsSerial: 'L6 SU-23', dateAcquired: 'MARCH 1, 2018', notes: 'Intel i3 - FUNCTIONAL'),
    HistoricalRecord(deskId: 'LAB6 - PC24', category: 'SYSTEM UNIT', brand: 'ACER', mfgSerial: 'DTVPUSPO637340578A9600', dntsSerial: 'L6 SU-24', dateAcquired: 'MARCH 1, 2018', notes: 'Intel i3 - FUNCTIONAL'),
    HistoricalRecord(deskId: 'LAB6 - PC25', category: 'SYSTEM UNIT', brand: 'ACER', mfgSerial: 'DTVPUSPO63734057759600', dntsSerial: 'L6 SU-25', dateAcquired: 'MARCH 1, 2018', notes: 'Intel i3 - FUNCTIONAL'),
    HistoricalRecord(deskId: 'LAB6 - PC26', category: 'SYSTEM UNIT', brand: 'ACER', mfgSerial: 'DTVPUSPO63734057719600', dntsSerial: 'L6 SU-26', dateAcquired: 'MARCH 1, 2018', notes: 'Intel i3 - FUNCTIONAL'),
    HistoricalRecord(deskId: 'LAB6 - PC27', category: 'SYSTEM UNIT', brand: 'ACER', mfgSerial: 'DTVPUSPO637340577E9600', dntsSerial: 'L6 SU-27', dateAcquired: 'MARCH 1, 2018', notes: 'Intel i3 - FUNCTIONAL'),
    HistoricalRecord(deskId: 'LAB6 - PC28', category: 'SYSTEM UNIT', brand: 'ACER', mfgSerial: 'DTVPUSPO63734057709600', dntsSerial: 'L6 SU-28', dateAcquired: 'MARCH 1, 2018', notes: 'Intel i3 - FUNCTIONAL'),
    HistoricalRecord(deskId: 'LAB6 - PC29', category: 'SYSTEM UNIT', brand: 'ACER', mfgSerial: 'DTVPUSPO637340577C9600', dntsSerial: 'L6 SU-29', dateAcquired: 'MARCH 1, 2018', notes: 'Intel i3 - FUNCTIONAL'),
    HistoricalRecord(deskId: 'LAB6 - PC30', category: 'SYSTEM UNIT', brand: 'ACER', mfgSerial: 'DTVPUSPO637340578E9600', dntsSerial: 'L6 SU-30', dateAcquired: 'MARCH 1, 2018', notes: 'Intel i3 - FUNCTIONAL'),
    HistoricalRecord(deskId: 'LAB6 - PC31', category: 'SYSTEM UNIT', brand: 'ACER', mfgSerial: 'DTVPUSPO637340576F9600', dntsSerial: 'L6 SU-31', dateAcquired: 'MARCH 1, 2018', notes: 'Intel i3 - FUNCTIONAL'),
    HistoricalRecord(deskId: 'LAB6 - PC32', category: 'SYSTEM UNIT', brand: 'ACER', mfgSerial: 'DTVPUSPO63734057949600', dntsSerial: 'L6 SU-32', dateAcquired: 'MARCH 1, 2018', notes: 'Intel i3 - FUNCTIONAL'),
    HistoricalRecord(deskId: 'LAB6 - PC33', category: 'SYSTEM UNIT', brand: 'ACER', mfgSerial: 'DTVPUSPO63734057769600', dntsSerial: 'L6 SU-33', dateAcquired: 'MARCH 1, 2018', notes: 'Intel i3 - FUNCTIONAL'),
    HistoricalRecord(deskId: 'LAB6 - PC34', category: 'SYSTEM UNIT', brand: 'ACER', mfgSerial: 'DTVPUSPO63734057899600', dntsSerial: 'L6 SU-34', dateAcquired: 'MARCH 1, 2018', notes: 'Intel i3 - FUNCTIONAL'),
    HistoricalRecord(deskId: 'LAB6 - PC35', category: 'SYSTEM UNIT', brand: 'ACER', mfgSerial: 'DTVPUSPO367340576D9600', dntsSerial: 'L6 SU-35', dateAcquired: 'MARCH 1, 2018', notes: 'Intel i3 - FUNCTIONAL'),
    HistoricalRecord(deskId: 'LAB6 - PC36', category: 'SYSTEM UNIT', brand: 'ACER', mfgSerial: 'DTVPUSPO63734057889600', dntsSerial: 'L6 SU-36', dateAcquired: 'MARCH 1, 2018', notes: 'Intel i3 - FUNCTIONAL'),
    HistoricalRecord(deskId: 'LAB6 - PC37', category: 'SYSTEM UNIT', brand: 'ACER', mfgSerial: 'DTVPUSPO637340578B9600', dntsSerial: 'L6 SU-37', dateAcquired: 'MARCH 1, 2018', notes: 'Intel i3 - FUNCTIONAL'),
    HistoricalRecord(deskId: 'LAB6 - PC38', category: 'SYSTEM UNIT', brand: 'ACER', mfgSerial: 'DTVPUSPO63734057849600', dntsSerial: 'L6 SU-38', dateAcquired: 'MARCH 1, 2018', notes: 'Intel i3 - FUNCTIONAL'),
    HistoricalRecord(deskId: 'LAB6 - PC39', category: 'SYSTEM UNIT', brand: 'ACER', mfgSerial: 'DTVPUSPO637340578C9600', dntsSerial: 'L6 SU-39', dateAcquired: 'MARCH 1, 2018', notes: 'Intel i3 - FUNCTIONAL'),
    HistoricalRecord(deskId: 'LAB6 - PC40', category: 'SYSTEM UNIT', brand: 'ACER', mfgSerial: 'DTVPUSPO637340576B9600', dntsSerial: 'L6 SU-40', dateAcquired: 'MARCH 1, 2018', notes: 'Intel i3 - FUNCTIONAL'),
    HistoricalRecord(deskId: 'LAB6 - PC41', category: 'SYSTEM UNIT', brand: 'LENOVO', mfgSerial: 'YL00HB5Z', dntsSerial: 'LAB5 SU - PC4', notes: 'Intel i7 - ACCOUNTING - FUNCTIONAL'),
    HistoricalRecord(deskId: 'LAB6 - PC42', category: 'SYSTEM UNIT', brand: 'ESGAMING', mfgSerial: 'NO_SERIAL_PC42', dntsSerial: 'LAB6 SU - PC42', notes: 'Intel i7 - DEFECTIVE'),
    HistoricalRecord(deskId: 'LAB6 - PC43', category: 'SYSTEM UNIT', brand: 'LENOVO', mfgSerial: 'YL00HB5M', dntsSerial: 'LAB5 SU-43', notes: 'Intel i7 - ACCOUNTING - FUNCTIONAL'),
    HistoricalRecord(deskId: 'LAB6 - PC44', category: 'SYSTEM UNIT', brand: 'LENOVO', mfgSerial: 'YL00HBJE', dntsSerial: 'L6 SU-44', notes: 'Intel i7 - REGISTRAR - FUNCTIONAL'),
    HistoricalRecord(deskId: 'LAB6 - PC45', category: 'SYSTEM UNIT', brand: 'LENOVO', mfgSerial: 'YL00HB5P', dntsSerial: 'LAB5 SU-45', notes: 'Intel i7 - ACCOUNTING - FUNCTIONAL'),
    HistoricalRecord(deskId: 'LAB6 - PC46', category: 'SYSTEM UNIT', brand: 'LENOVO', mfgSerial: 'YL00HB5K', dntsSerial: 'LAB5 SU-46', notes: 'Intel i7 - ID PROCESSING / PIT-OS - FUNCTIONAL'),
    HistoricalRecord(deskId: 'LAB6 - PC47', category: 'SYSTEM UNIT', brand: 'LENOVO', mfgSerial: 'YL00HB5F', dntsSerial: 'LAB5 SU-44', notes: 'Intel i7 - ACCOUNTING - FUNCTIONAL'),
    HistoricalRecord(deskId: 'LAB6 - PC48', category: 'SYSTEM UNIT', brand: 'LENOVO', mfgSerial: 'YL00HB60', dntsSerial: 'LAB5 SU-48', notes: 'Intel i7 - ACCOUNTING - FUNCTIONAL'),

    // ═══════════════════════════════════════════════════════════════════════════
    // KEYBOARDS
    // ═══════════════════════════════════════════════════════════════════════════
    HistoricalRecord(deskId: 'LAB6 - PC1', category: 'KEYBOARD', brand: 'ACER', mfgSerial: '73180FA3K701', dntsSerial: 'L6-K-01', dateAcquired: 'MARCH 1, 2018', notes: 'FUNCTIONAL'),
    HistoricalRecord(deskId: 'LAB6 - PC2', category: 'KEYBOARD', brand: 'ACER', mfgSerial: '73180F70K701', dntsSerial: 'L6-K-02', dateAcquired: 'MARCH 1, 2018', notes: 'FUNCTIONAL'),
    HistoricalRecord(deskId: 'LAB6 - PC3', category: 'KEYBOARD', brand: 'ACER', mfgSerial: '73180F7EK701', dntsSerial: 'L6-K-03', dateAcquired: 'MARCH 1, 2018', notes: 'FUNCTIONAL'),
    HistoricalRecord(deskId: 'LAB6 - PC4', category: 'KEYBOARD', brand: 'ACER', mfgSerial: '73180F32K701', dntsSerial: 'L6-K-04', dateAcquired: 'MARCH 1, 2018', notes: 'FUNCTIONAL'),
    HistoricalRecord(deskId: 'LAB6 - PC5', category: 'KEYBOARD', brand: 'ACER', mfgSerial: '731810C1K701', dntsSerial: 'L6-K-05', dateAcquired: 'MARCH 1, 2018', notes: 'FUNCTIONAL'),
    HistoricalRecord(deskId: 'LAB6 - PC6', category: 'KEYBOARD', brand: 'ACER', mfgSerial: '731810F2DK701', dntsSerial: 'L6-K-06', dateAcquired: 'MARCH 1, 2018', notes: 'FUNCTIONAL'),
    HistoricalRecord(deskId: 'LAB6 - PC7', category: 'KEYBOARD', brand: 'ACER', mfgSerial: '73380207K701', dntsSerial: 'L6-K-07', dateAcquired: 'MARCH 1, 2018', notes: 'FUNCTIONAL'),
    HistoricalRecord(deskId: 'LAB6 - PC8', category: 'KEYBOARD', brand: 'ACER', mfgSerial: '731810CDK701', dntsSerial: 'L6-K-08', dateAcquired: 'MARCH 1, 2018', notes: 'FUNCTIONAL'),
    HistoricalRecord(deskId: 'LAB6 - PC9', category: 'KEYBOARD', brand: 'ACER', mfgSerial: '73180F2FK701', dntsSerial: 'L6-K-09', dateAcquired: 'MARCH 1, 2018', notes: 'FUNCTIONAL'),
    HistoricalRecord(deskId: 'LAB6 - PC10', category: 'KEYBOARD', brand: 'ACER', mfgSerial: '73180F2EK701', dntsSerial: 'L6-K-10', dateAcquired: 'MARCH 1, 2018', notes: 'FUNCTIONAL'),
    HistoricalRecord(deskId: 'LAB6 - PC11', category: 'KEYBOARD', brand: 'A4TECH', mfgSerial: 'NO_SERIAL_K11', dntsSerial: 'L6-K-11', notes: 'FUNCTIONAL'),
    HistoricalRecord(deskId: 'LAB6 - PC12', category: 'KEYBOARD', brand: 'ACER', mfgSerial: '73380670K701', dntsSerial: 'L6-K-12', dateAcquired: 'MARCH 1, 2018', notes: 'FUNCTIONAL'),
    HistoricalRecord(deskId: 'LAB6 - PC13', category: 'KEYBOARD', brand: 'ACER', mfgSerial: '731810CAK701', dntsSerial: 'L6-K-13', dateAcquired: 'MARCH 1, 2018', notes: 'FUNCTIONAL'),
    HistoricalRecord(deskId: 'LAB6 - PC14', category: 'KEYBOARD', brand: 'ACER', mfgSerial: '73180FA0K701', dntsSerial: 'L6-K-14', dateAcquired: 'MARCH 1, 2018', notes: 'FUNCTIONAL'),
    HistoricalRecord(deskId: 'LAB6 - PC15', category: 'KEYBOARD', brand: 'A4TECH', mfgSerial: 'NO_SERIAL_K15', dntsSerial: 'L6-K-15', notes: 'FUNCTIONAL'),
    HistoricalRecord(deskId: 'LAB6 - PC16', category: 'KEYBOARD', brand: 'ACER', mfgSerial: '731810CBK701', dntsSerial: 'L6-K-16', dateAcquired: 'MARCH 1, 2018', notes: 'FUNCTIONAL'),
    HistoricalRecord(deskId: 'LAB6 - PC17', category: 'KEYBOARD', brand: 'ACER', mfgSerial: '731810C5K701', dntsSerial: 'L6-K-17', dateAcquired: 'MARCH 1, 2018', notes: 'FUNCTIONAL'),
    HistoricalRecord(deskId: 'LAB6 - PC18', category: 'KEYBOARD', brand: 'ACER', mfgSerial: '73180F29K701', dntsSerial: 'L6-K-18', dateAcquired: 'MARCH 1, 2018', notes: 'FUNCTIONAL'),
    HistoricalRecord(deskId: 'LAB6 - PC19', category: 'KEYBOARD', brand: 'ACER', mfgSerial: '73180F7CK701', dntsSerial: 'L6-K-19', dateAcquired: 'MARCH 1, 2018', notes: 'FUNCTIONAL'),
    HistoricalRecord(deskId: 'LAB6 - PC20', category: 'KEYBOARD', brand: 'ACER', mfgSerial: '73380213K701', dntsSerial: 'L6-K-20', dateAcquired: 'MARCH 1, 2018', notes: 'FUNCTIONAL'),
    HistoricalRecord(deskId: 'LAB6 - PC21', category: 'KEYBOARD', brand: 'ACER', mfgSerial: '73380683K701', dntsSerial: 'L6-K-21', dateAcquired: 'MARCH 1, 2018', notes: 'FUNCTIONAL'),
    HistoricalRecord(deskId: 'LAB6 - PC22', category: 'KEYBOARD', brand: 'ACER', mfgSerial: '73380214K701', dntsSerial: 'L6-K-22', dateAcquired: 'MARCH 1, 2018', notes: 'FUNCTIONAL'),
    HistoricalRecord(deskId: 'LAB6 - PC23', category: 'KEYBOARD', brand: 'ACER', mfgSerial: '731810C4K701', dntsSerial: 'L6-K-23', dateAcquired: 'MARCH 1, 2018', notes: 'FUNCTIONAL'),
    HistoricalRecord(deskId: 'LAB6 - PC24', category: 'KEYBOARD', brand: 'ACER', mfgSerial: '731810C2K701', dntsSerial: 'L6-K-24', dateAcquired: 'MARCH 1, 2018', notes: 'FUNCTIONAL'),
    HistoricalRecord(deskId: 'LAB6 - PC25', category: 'KEYBOARD', brand: 'ACER', mfgSerial: '731810C8K701', dntsSerial: 'L6-K-25', dateAcquired: 'MARCH 1, 2018', notes: 'FUNCTIONAL'),
    HistoricalRecord(deskId: 'LAB6 - PC26', category: 'KEYBOARD', brand: 'ACER', mfgSerial: '73180F3K701', dntsSerial: 'L6-K-26', dateAcquired: 'MARCH 1, 2018', notes: 'FUNCTIONAL'),
    HistoricalRecord(deskId: 'LAB6 - PC27', category: 'KEYBOARD', brand: 'ACER', mfgSerial: '73180F59K701', dntsSerial: 'L6-K-27', dateAcquired: 'MARCH 1, 2018', notes: 'FUNCTIONAL'),
    HistoricalRecord(deskId: 'LAB6 - PC28', category: 'KEYBOARD', brand: 'ACER', mfgSerial: '731810D0K701', dntsSerial: 'L6-K-28', dateAcquired: 'MARCH 1, 2018', notes: 'FUNCTIONAL'),
    HistoricalRecord(deskId: 'LAB6 - PC29', category: 'KEYBOARD', brand: 'ACER', mfgSerial: '73180F2AK701', dntsSerial: 'L6-K-29', dateAcquired: 'MARCH 1, 2018', notes: 'FUNCTIONAL'),
    HistoricalRecord(deskId: 'LAB6 - PC30', category: 'KEYBOARD', brand: 'ACER', mfgSerial: '73180F79K701', dntsSerial: 'L6-K-30', dateAcquired: 'MARCH 1, 2018', notes: 'FUNCTIONAL'),
    HistoricalRecord(deskId: 'LAB6 - PC31', category: 'KEYBOARD', brand: 'ACER', mfgSerial: '733800679K701', dntsSerial: 'L6-K-31', dateAcquired: 'MARCH 1, 2018', notes: 'FUNCTIONAL'),
    HistoricalRecord(deskId: 'LAB6 - PC32', category: 'KEYBOARD', brand: 'ACER', mfgSerial: '73180F28K701', dntsSerial: 'L6-K-32', dateAcquired: 'MARCH 1, 2018', notes: 'FUNCTIONAL'),
    HistoricalRecord(deskId: 'LAB6 - PC33', category: 'KEYBOARD', brand: 'ACER', mfgSerial: '73180C4CK701', dntsSerial: 'L6-K-33', dateAcquired: 'MARCH 1, 2018', notes: 'FUNCTIONAL'),
    HistoricalRecord(deskId: 'LAB6 - PC34', category: 'KEYBOARD', brand: 'ACER', mfgSerial: '73180F31K701', dntsSerial: 'L6-K-34', dateAcquired: 'MARCH 1, 2018', notes: 'FUNCTIONAL'),
    HistoricalRecord(deskId: 'LAB6 - PC35', category: 'KEYBOARD', brand: 'ACER', mfgSerial: '625808D7K701', dntsSerial: 'L6-K-35', dateAcquired: 'MARCH 1, 2018', notes: 'FUNCTIONAL'),
    HistoricalRecord(deskId: 'LAB6 - PC36', category: 'KEYBOARD', brand: 'ACER', mfgSerial: '73180F6FK701', dntsSerial: 'L6-K-36', dateAcquired: 'MARCH 1, 2018', notes: 'FUNCTIONAL'),
    HistoricalRecord(deskId: 'LAB6 - PC37', category: 'KEYBOARD', brand: 'ACER', mfgSerial: '73180F33K701', dntsSerial: 'L6-K-37', dateAcquired: 'MARCH 1, 2018', notes: 'FUNCTIONAL'),
    HistoricalRecord(deskId: 'LAB6 - PC38', category: 'KEYBOARD', brand: 'A4TECH', mfgSerial: '23XWU00_K38', dntsSerial: 'L6-K-38', notes: 'FUNCTIONAL'),
    HistoricalRecord(deskId: 'LAB6 - PC39', category: 'KEYBOARD', brand: 'ACER', mfgSerial: '73180FAFK701', dntsSerial: 'L6-K-39', dateAcquired: 'MARCH 1, 2018', notes: 'FUNCTIONAL'),
    HistoricalRecord(deskId: 'LAB6 - PC40', category: 'KEYBOARD', brand: 'ACER', mfgSerial: '73380211K701', dntsSerial: 'L6-K-40', dateAcquired: 'MARCH 1, 2018', notes: 'FUNCTIONAL'),
    HistoricalRecord(deskId: 'LAB6 - PC41', category: 'KEYBOARD', brand: 'A4TECH', mfgSerial: '23XWU00_K41', dntsSerial: 'L6-K-41', notes: 'FUNCTIONAL'),
    HistoricalRecord(deskId: 'LAB6 - PC42', category: 'KEYBOARD', brand: 'A4TECH', mfgSerial: '23XWU00_K42', dntsSerial: 'L6-K-42', notes: 'FUNCTIONAL'),
    HistoricalRecord(deskId: 'LAB6 - PC43', category: 'KEYBOARD', brand: 'A4TECH', mfgSerial: '23XWU00_K43', dntsSerial: 'L6-K-43', notes: 'FUNCTIONAL'),
    HistoricalRecord(deskId: 'LAB6 - PC44', category: 'KEYBOARD', brand: 'A4TECH', mfgSerial: '23XWU00_K44', dntsSerial: 'L6-K-44', notes: 'FUNCTIONAL'),
    HistoricalRecord(deskId: 'LAB6 - PC45', category: 'KEYBOARD', brand: 'A4TECH', mfgSerial: '23XWU00_K45', dntsSerial: 'L6-K-45', notes: 'FUNCTIONAL'),
    HistoricalRecord(deskId: 'LAB6 - PC46', category: 'KEYBOARD', brand: 'A4TECH', mfgSerial: '23XWU00_K46', dntsSerial: 'L6-K-46', notes: 'FUNCTIONAL'),
    HistoricalRecord(deskId: 'LAB6 - PC47', category: 'KEYBOARD', brand: 'A4TECH', mfgSerial: '23XWU00_LAB5_K46', dntsSerial: 'LAB 5-K-46', notes: 'ID PROCESSING / PIT-OS - FUNCTIONAL'),
    HistoricalRecord(deskId: 'LAB6 - PC48', category: 'KEYBOARD', brand: 'ACER', mfgSerial: '23XWU00_LAB5_K31', dntsSerial: 'LAB 5-K-31', notes: 'ACCOUNTING - FUNCTIONAL'),

    // ═══════════════════════════════════════════════════════════════════════════
    // MICE
    // ═══════════════════════════════════════════════════════════════════════════
    HistoricalRecord(deskId: 'LAB6 - PC1', category: 'MOUSE', brand: 'ACER', mfgSerial: 'NO_SERIAL_M01', dntsSerial: 'L6-M-01', notes: 'FUNCTIONAL'),
    HistoricalRecord(deskId: 'LAB6 - PC2', category: 'MOUSE', brand: 'ACER', mfgSerial: 'NO_SERIAL_M02', dntsSerial: 'L6-M-02', notes: 'FUNCTIONAL'),
    HistoricalRecord(deskId: 'LAB6 - PC3', category: 'MOUSE', brand: 'ACER', mfgSerial: '73107976K701', dntsSerial: 'L6-M-03', notes: 'FUNCTIONAL'),
    HistoricalRecord(deskId: 'LAB6 - PC4', category: 'MOUSE', brand: 'ACER', mfgSerial: '73107950K701', dntsSerial: 'L6-M-04', notes: 'FUNCTIONAL'),
    HistoricalRecord(deskId: 'LAB6 - PC5', category: 'MOUSE', brand: 'ACER', mfgSerial: '7310797DK701', dntsSerial: 'L6-M-05', notes: 'FUNCTIONAL'),
    HistoricalRecord(deskId: 'LAB6 - PC6', category: 'MOUSE', brand: 'ACER', mfgSerial: 'NO_SERIAL_M06', dntsSerial: 'L6-M-06', notes: 'FUNCTIONAL'),
    HistoricalRecord(deskId: 'LAB6 - PC7', category: 'MOUSE', brand: 'ACER', mfgSerial: '73107960K701', dntsSerial: 'L6-M-07', notes: 'FUNCTIONAL'),
    HistoricalRecord(deskId: 'LAB6 - PC8', category: 'MOUSE', brand: 'ACER', mfgSerial: '73107966K701', dntsSerial: 'L6-M-08', notes: 'FUNCTIONAL'),
    HistoricalRecord(deskId: 'LAB6 - PC9', category: 'MOUSE', brand: 'ACER', mfgSerial: 'NO_SERIAL_M09', dntsSerial: 'L6-M-09', notes: 'FUNCTIONAL'),
    HistoricalRecord(deskId: 'LAB6 - PC10', category: 'MOUSE', brand: 'ACER', mfgSerial: '73107971K701', dntsSerial: 'L6-M-10', notes: 'FUNCTIONAL'),
    HistoricalRecord(deskId: 'LAB6 - PC11', category: 'MOUSE', brand: 'ACER', mfgSerial: '73107978K701', dntsSerial: 'L6-M-11', notes: 'FUNCTIONAL'),
    HistoricalRecord(deskId: 'LAB6 - PC12', category: 'MOUSE', brand: 'ACER', mfgSerial: 'NO_SERIAL_M12', dntsSerial: 'L6-M-12', notes: 'FUNCTIONAL'),
    HistoricalRecord(deskId: 'LAB6 - PC13', category: 'MOUSE', brand: 'ACER', mfgSerial: '73107968K701', dntsSerial: 'L6-M-13', notes: 'FUNCTIONAL'),
    HistoricalRecord(deskId: 'LAB6 - PC14', category: 'MOUSE', brand: 'ACER', mfgSerial: 'NO_SERIAL_M14', dntsSerial: 'L6-M-14', notes: 'FUNCTIONAL'),
    HistoricalRecord(deskId: 'LAB6 - PC15', category: 'MOUSE', brand: 'ACER', mfgSerial: '73107951K701', dntsSerial: 'L6-M-15', notes: 'FUNCTIONAL'),
    HistoricalRecord(deskId: 'LAB6 - PC16', category: 'MOUSE', brand: 'ACER', mfgSerial: '73107959K701', dntsSerial: 'L6-M-16', notes: 'FUNCTIONAL'),
    HistoricalRecord(deskId: 'LAB6 - PC17', category: 'MOUSE', brand: 'ACER', mfgSerial: '7310797EK701', dntsSerial: 'L6-M-17', notes: 'FUNCTIONAL'),
    HistoricalRecord(deskId: 'LAB6 - PC18', category: 'MOUSE', brand: 'ACER', mfgSerial: 'NO_SERIAL_M18', dntsSerial: 'L6-M-18', notes: 'FUNCTIONAL'),
    HistoricalRecord(deskId: 'LAB6 - PC19', category: 'MOUSE', brand: 'ACER', mfgSerial: '73107969K701', dntsSerial: 'L6-M-19', notes: 'FUNCTIONAL'),
    HistoricalRecord(deskId: 'LAB6 - PC20', category: 'MOUSE', brand: 'ACER', mfgSerial: 'NO_SERIAL_M20', dntsSerial: 'L6-M-20', notes: 'FUNCTIONAL'),
    HistoricalRecord(deskId: 'LAB6 - PC21', category: 'MOUSE', brand: 'ACER', mfgSerial: '73107952K701', dntsSerial: 'L6-M-21', notes: 'FUNCTIONAL'),
    HistoricalRecord(deskId: 'LAB6 - PC22', category: 'MOUSE', brand: 'ACER', mfgSerial: '73107972K701', dntsSerial: 'L6-M-22', notes: 'FUNCTIONAL'),
    HistoricalRecord(deskId: 'LAB6 - PC23', category: 'MOUSE', brand: 'ACER', mfgSerial: 'NO_SERIAL_M23', dntsSerial: 'L6-M-23', notes: 'FUNCTIONAL'),
    HistoricalRecord(deskId: 'LAB6 - PC24', category: 'MOUSE', brand: 'ACER', mfgSerial: 'NO_SERIAL_M24', dntsSerial: 'L6-M-24', notes: 'FUNCTIONAL'),
    HistoricalRecord(deskId: 'LAB6 - PC25', category: 'MOUSE', brand: 'ACER', mfgSerial: '73107961K701', dntsSerial: 'L6-M-25', notes: 'FUNCTIONAL'),
    HistoricalRecord(deskId: 'LAB6 - PC26', category: 'MOUSE', brand: 'ACER', mfgSerial: '73107962K701', dntsSerial: 'L6-M-26', notes: 'FUNCTIONAL'),
    HistoricalRecord(deskId: 'LAB6 - PC27', category: 'MOUSE', brand: 'ACER', mfgSerial: 'NO_SERIAL_M27', dntsSerial: 'L6-M-27', notes: 'FUNCTIONAL'),
    HistoricalRecord(deskId: 'LAB6 - PC28', category: 'MOUSE', brand: 'ACER', mfgSerial: '73107977K701', dntsSerial: 'L6-M-28', notes: 'FUNCTIONAL'),
    HistoricalRecord(deskId: 'LAB6 - PC29', category: 'MOUSE', brand: 'ACER', mfgSerial: 'NO_SERIAL_M29', dntsSerial: 'L6-M-29', notes: 'FUNCTIONAL'),
    HistoricalRecord(deskId: 'LAB6 - PC30', category: 'MOUSE', brand: 'ACER', mfgSerial: '73107974K701', dntsSerial: 'L6-M-30', notes: 'FUNCTIONAL'),
    HistoricalRecord(deskId: 'LAB6 - PC31', category: 'MOUSE', brand: 'ACER', mfgSerial: '7310794FK701', dntsSerial: 'L6-M-31', notes: 'FUNCTIONAL'),
    HistoricalRecord(deskId: 'LAB6 - PC32', category: 'MOUSE', brand: 'ACER', mfgSerial: '622070D8K701', dntsSerial: 'L6-M-32', notes: 'FUNCTIONAL'),
    HistoricalRecord(deskId: 'LAB6 - PC33', category: 'MOUSE', brand: 'ACER', mfgSerial: '7310797AK701', dntsSerial: 'L6-M-33', notes: 'FUNCTIONAL'),
    HistoricalRecord(deskId: 'LAB6 - PC34', category: 'MOUSE', brand: 'ACER', mfgSerial: 'NO_SERIAL_M34', dntsSerial: 'L6-M-34', notes: 'FUNCTIONAL'),
    HistoricalRecord(deskId: 'LAB6 - PC35', category: 'MOUSE', brand: 'ACER', mfgSerial: 'NO_SERIAL_M35', dntsSerial: 'L6-M-35', notes: 'FUNCTIONAL'),
    HistoricalRecord(deskId: 'LAB6 - PC36', category: 'MOUSE', brand: 'ACER', mfgSerial: '7310796BK701', dntsSerial: 'L6-M-36', notes: 'FUNCTIONAL'),
    HistoricalRecord(deskId: 'LAB6 - PC37', category: 'MOUSE', brand: 'ACER', mfgSerial: '731043ECK701', dntsSerial: 'L6-M-37', notes: 'FUNCTIONAL'),
    HistoricalRecord(deskId: 'LAB6 - PC38', category: 'MOUSE', brand: 'ACER', mfgSerial: '731043ECK701_M38', dntsSerial: 'L6-M-38', notes: 'FUNCTIONAL'),
    HistoricalRecord(deskId: 'LAB6 - PC39', category: 'MOUSE', brand: 'ACER', mfgSerial: 'NO_SERIAL_M39', dntsSerial: 'L6-M-39', notes: 'FUNCTIONAL'),
    HistoricalRecord(deskId: 'LAB6 - PC40', category: 'MOUSE', brand: 'ACER', mfgSerial: 'NO_SERIAL_M40', dntsSerial: 'L6-M-40', notes: 'FUNCTIONAL'),
    HistoricalRecord(deskId: 'LAB6 - PC41', category: 'MOUSE', brand: 'A4TECH', mfgSerial: '23YWU01_M41', dntsSerial: 'L6-M-41', notes: 'FUNCTIONAL'),
    HistoricalRecord(deskId: 'LAB6 - PC42', category: 'MOUSE', brand: 'A4TECH', mfgSerial: '23YWU01_M42', dntsSerial: 'L6-M-42', notes: 'FUNCTIONAL'),
    HistoricalRecord(deskId: 'LAB6 - PC43', category: 'MOUSE', brand: 'A4TECH', mfgSerial: '23YWU01_M43', dntsSerial: 'L6-M-43', notes: 'FUNCTIONAL'),
    HistoricalRecord(deskId: 'LAB6 - PC44', category: 'MOUSE', brand: 'A4TECH', mfgSerial: '23YWU01_M44', dntsSerial: 'L6-M-44', notes: 'FUNCTIONAL'),
    HistoricalRecord(deskId: 'LAB6 - PC45', category: 'MOUSE', brand: 'A4TECH', mfgSerial: '23YWU01_M45', dntsSerial: 'L6-M-45', notes: 'DEFECTIVE'),
    HistoricalRecord(deskId: 'LAB6 - PC46', category: 'MOUSE', brand: 'A4TECH', mfgSerial: '23YWU01_M46', dntsSerial: 'L6-M-46', notes: 'DEFECTIVE'),
    HistoricalRecord(deskId: 'LAB6 - PC47', category: 'MOUSE', brand: 'A4TECH', mfgSerial: '23XWU01_LAB5_M46', dntsSerial: 'LAB 5-M-46', notes: 'ID PROCESSING / PIT OS - FUNCTIONAL'),
    HistoricalRecord(deskId: 'LAB6 - PC48', category: 'MOUSE', brand: 'ACER', mfgSerial: '7310794FK701_LAB5_M31', dntsSerial: 'LAB 5-M-31', notes: 'ACCOUNTING - FUNCTIONAL'),

    // ═══════════════════════════════════════════════════════════════════════════
    // AVRs
    // ═══════════════════════════════════════════════════════════════════════════
    HistoricalRecord(deskId: 'LAB6 - PC1', category: 'AVR', brand: 'SECURE', mfgSerial: 'L6-AVR-01', dntsSerial: 'L6-AVR-01', notes: 'FUNCTIONAL'),
    HistoricalRecord(deskId: 'LAB6 - PC2', category: 'AVR', brand: 'SECURE', mfgSerial: 'L6-AVR-02', dntsSerial: 'L6-AVR-02', notes: 'FUNCTIONAL'),
    HistoricalRecord(deskId: 'LAB6 - PC3', category: 'AVR', brand: 'POWER', mfgSerial: 'L6-AVR-03', dntsSerial: 'L6-AVR-03', notes: 'FUNCTIONAL'),
    HistoricalRecord(deskId: 'LAB6 - PC4', category: 'AVR', brand: 'SECURE', mfgSerial: 'L6-AVR-04', dntsSerial: 'L6-AVR-04', notes: 'FUNCTIONAL'),
    HistoricalRecord(deskId: 'LAB6 - PC5', category: 'AVR', brand: 'SECURE', mfgSerial: 'L6-AVR-05', dntsSerial: 'L6-AVR-05', notes: 'FUNCTIONAL'),
    HistoricalRecord(deskId: 'LAB6 - PC6', category: 'AVR', brand: 'SECURE', mfgSerial: 'L6-AVR-06', dntsSerial: 'L6-AVR-06', notes: 'FUNCTIONAL'),
    HistoricalRecord(deskId: 'LAB6 - PC7', category: 'AVR', brand: 'SECURE', mfgSerial: 'L6-AVR-07', dntsSerial: 'L6-AVR-07', notes: 'FUNCTIONAL'),
    HistoricalRecord(deskId: 'LAB6 - PC8', category: 'AVR', brand: 'SECURE', mfgSerial: 'L6-AVR-08', dntsSerial: 'L6-AVR-08', notes: 'FUNCTIONAL'),
    HistoricalRecord(deskId: 'LAB6 - PC9', category: 'AVR', brand: 'POWER', mfgSerial: 'L6-AVR-09', dntsSerial: 'L6-AVR-09', notes: 'FUNCTIONAL'),
    HistoricalRecord(deskId: 'LAB6 - PC10', category: 'AVR', brand: 'SECURE', mfgSerial: 'L6-AVR-10', dntsSerial: 'L6-AVR-10', notes: 'FUNCTIONAL'),
    HistoricalRecord(deskId: 'LAB6 - PC11', category: 'AVR', brand: 'MONSTER', mfgSerial: 'L6-AVR-11', dntsSerial: 'L6-AVR-11', notes: 'FUNCTIONAL'),
    HistoricalRecord(deskId: 'LAB6 - PC12', category: 'AVR', brand: 'SECURE', mfgSerial: 'L6-AVR-12', dntsSerial: 'L6-AVR-12', notes: 'FUNCTIONAL'),
    HistoricalRecord(deskId: 'LAB6 - PC13', category: 'AVR', brand: 'SECURE', mfgSerial: 'L6-AVR-13', dntsSerial: 'L6-AVR-13', notes: 'FUNCTIONAL'),
    HistoricalRecord(deskId: 'LAB6 - PC14', category: 'AVR', brand: 'SECURE', mfgSerial: 'L6-AVR-14', dntsSerial: 'L6-AVR-14', notes: 'FUNCTIONAL'),
    HistoricalRecord(deskId: 'LAB6 - PC15', category: 'AVR', brand: 'SECURE', mfgSerial: 'L6-AVR-15', dntsSerial: 'L6-AVR-15', notes: 'FUNCTIONAL'),
    HistoricalRecord(deskId: 'LAB6 - PC16', category: 'AVR', brand: 'SECURE', mfgSerial: 'L6-AVR-16', dntsSerial: 'L6-AVR-16', notes: 'FUNCTIONAL'),
    HistoricalRecord(deskId: 'LAB6 - PC17', category: 'AVR', brand: 'SECURE', mfgSerial: 'L6-AVR-17', dntsSerial: 'L6-AVR-17', notes: 'FUNCTIONAL'),
    HistoricalRecord(deskId: 'LAB6 - PC18', category: 'AVR', brand: 'MONSTER', mfgSerial: 'L6-AVR-18', dntsSerial: 'L6-AVR-18', notes: 'FUNCTIONAL'),
    HistoricalRecord(deskId: 'LAB6 - PC19', category: 'AVR', brand: 'SECURE', mfgSerial: 'L6-AVR-19', dntsSerial: 'L6-AVR-19', notes: 'FUNCTIONAL'),
    HistoricalRecord(deskId: 'LAB6 - PC20', category: 'AVR', brand: 'SECURE', mfgSerial: 'L6-AVR-20', dntsSerial: 'L6-AVR-20', notes: 'FUNCTIONAL'),
    HistoricalRecord(deskId: 'LAB6 - PC21', category: 'AVR', brand: 'SECURE', mfgSerial: 'L6-AVR-21', dntsSerial: 'L6-AVR-21', notes: 'FUNCTIONAL'),
    HistoricalRecord(deskId: 'LAB6 - PC22', category: 'AVR', brand: 'POWER', mfgSerial: 'L6-AVR-22', dntsSerial: 'L6-AVR-22', notes: 'FUNCTIONAL'),
    HistoricalRecord(deskId: 'LAB6 - PC23', category: 'AVR', brand: 'SECURE', mfgSerial: 'L6-AVR-23', dntsSerial: 'L6-AVR-23', notes: 'FUNCTIONAL'),
    HistoricalRecord(deskId: 'LAB6 - PC24', category: 'AVR', brand: 'SECURE', mfgSerial: 'L6-AVR-24', dntsSerial: 'L6-AVR-24', notes: 'FUNCTIONAL'),
    HistoricalRecord(deskId: 'LAB6 - PC25', category: 'AVR', brand: 'SECURE', mfgSerial: 'L6-AVR-25', dntsSerial: 'L6-AVR-25', notes: 'FUNCTIONAL'),
    HistoricalRecord(deskId: 'LAB6 - PC26', category: 'AVR', brand: 'SECURE', mfgSerial: 'L6-AVR-26', dntsSerial: 'L6-AVR-26', notes: 'FUNCTIONAL'),
    HistoricalRecord(deskId: 'LAB6 - PC27', category: 'AVR', brand: 'SECURE', mfgSerial: 'L6-AVR-27', dntsSerial: 'L6-AVR-27', notes: 'FUNCTIONAL'),
    HistoricalRecord(deskId: 'LAB6 - PC28', category: 'AVR', brand: 'SECURE', mfgSerial: 'L6-AVR-28', dntsSerial: 'L6-AVR-28', notes: 'FUNCTIONAL'),
    HistoricalRecord(deskId: 'LAB6 - PC29', category: 'AVR', brand: 'POWER', mfgSerial: 'L6-AVR-29', dntsSerial: 'L6-AVR-29', notes: 'FUNCTIONAL'),
    HistoricalRecord(deskId: 'LAB6 - PC30', category: 'AVR', brand: 'MONSTER', mfgSerial: 'L6-AVR-30', dntsSerial: 'L6-AVR-30', notes: 'FUNCTIONAL'),
    HistoricalRecord(deskId: 'LAB6 - PC31', category: 'AVR', brand: 'POWER', mfgSerial: 'L6-AVR-31', dntsSerial: 'L6-AVR-31', notes: 'FUNCTIONAL'),
    HistoricalRecord(deskId: 'LAB6 - PC32', category: 'AVR', brand: 'SECURE', mfgSerial: 'L6-AVR-32', dntsSerial: 'L6-AVR-32', notes: 'FUNCTIONAL'),
    HistoricalRecord(deskId: 'LAB6 - PC33', category: 'AVR', brand: 'SECURE', mfgSerial: 'L6-AVR-33', dntsSerial: 'L6-AVR-33', notes: 'FUNCTIONAL'),
    HistoricalRecord(deskId: 'LAB6 - PC34', category: 'AVR', brand: 'SECURE', mfgSerial: 'L6-AVR-34', dntsSerial: 'L6-AVR-34', notes: 'FUNCTIONAL'),
    HistoricalRecord(deskId: 'LAB6 - PC35', category: 'AVR', brand: 'SECURE', mfgSerial: 'L6-AVR-35', dntsSerial: 'L6-AVR-35', notes: 'FUNCTIONAL'),
    HistoricalRecord(deskId: 'LAB6 - PC36', category: 'AVR', brand: 'SECURE', mfgSerial: 'L6-AVR-36', dntsSerial: 'L6-AVR-36', notes: 'FUNCTIONAL'),
    HistoricalRecord(deskId: 'LAB6 - PC37', category: 'AVR', brand: 'SECURE', mfgSerial: 'L6-AVR-37', dntsSerial: 'L6-AVR-37', notes: 'FUNCTIONAL'),
    HistoricalRecord(deskId: 'LAB6 - PC38', category: 'AVR', brand: 'SECURE', mfgSerial: 'L6-AVR-38', dntsSerial: 'L6-AVR-38', notes: 'FUNCTIONAL'),
    HistoricalRecord(deskId: 'LAB6 - PC39', category: 'AVR', brand: 'SECURE', mfgSerial: 'L6-AVR-39', dntsSerial: 'L6-AVR-39', notes: 'FUNCTIONAL'),
    HistoricalRecord(deskId: 'LAB6 - PC40', category: 'AVR', brand: 'SECURE', mfgSerial: 'L6-AVR-40', dntsSerial: 'L6-AVR-40', notes: 'FUNCTIONAL'),
    HistoricalRecord(deskId: 'LAB6 - PC41', category: 'AVR', brand: 'SECURE', mfgSerial: 'L6-AVR-41', dntsSerial: 'L6-AVR-41', notes: 'FUNCTIONAL'),
    HistoricalRecord(deskId: 'LAB6 - PC42', category: 'AVR', brand: 'SECURE', mfgSerial: 'L6-AVR-42', dntsSerial: 'L6-AVR-42', notes: 'FUNCTIONAL'),
    HistoricalRecord(deskId: 'LAB6 - PC43', category: 'AVR', brand: 'SECURE', mfgSerial: 'L6-AVR-43', dntsSerial: 'L6-AVR-43', notes: 'FUNCTIONAL'),
    HistoricalRecord(deskId: 'LAB6 - PC44', category: 'AVR', brand: 'SECURE', mfgSerial: 'L6-AVR-44', dntsSerial: 'L6-AVR-44', notes: 'FUNCTIONAL'),
    HistoricalRecord(deskId: 'LAB6 - PC45', category: 'AVR', brand: 'SECURE', mfgSerial: 'L6-AVR-45', dntsSerial: 'L6-AVR-45', notes: 'FUNCTIONAL'),
    HistoricalRecord(deskId: 'LAB6 - PC46', category: 'AVR', brand: 'SECURE', mfgSerial: 'L6-AVR-46', dntsSerial: 'L6-AVR-46', notes: 'FUNCTIONAL'),
    HistoricalRecord(deskId: 'LAB6 - PC47', category: 'AVR', brand: 'SECURE', mfgSerial: 'LAB 5-AVR-46', dntsSerial: 'LAB 5-AVR-46', notes: 'ID PROCESSING / PIT-OS - FUNCTIONAL'),
    HistoricalRecord(deskId: 'LAB6 - PC48', category: 'AVR', brand: 'SECURE', mfgSerial: 'LAB 5-AVR-40', dntsSerial: 'LAB 5-AVR-40', notes: 'ACCOUNTING - FUNCTIONAL'),

    // ═══════════════════════════════════════════════════════════════════════════
    // SSDs (Merged from previous baseline)
    // ═══════════════════════════════════════════════════════════════════════════
    HistoricalRecord(deskId: 'LAB6 - PC1', category: 'SSD', dntsSerial: 'L6-D01-SSD', mfgSerial: '50026B727302C7E0', brand: 'KINGSTON', notes: 'FUNCTIONAL'),
    HistoricalRecord(deskId: 'LAB6 - PC2', category: 'SSD', dntsSerial: 'L6-D02-SSD', mfgSerial: '50026B727302CCB4', brand: 'KINGSTON', notes: 'FUNCTIONAL'),
    HistoricalRecord(deskId: 'LAB6 - PC3', category: 'SSD', dntsSerial: 'L6-D03-SSD', mfgSerial: '50026B727302C687', brand: 'KINGSTON', notes: 'FUNCTIONAL'),
    HistoricalRecord(deskId: 'LAB6 - PC4', category: 'SSD', dntsSerial: 'L6-D04-SSD', mfgSerial: '50026B727302C6E2', brand: 'KINGSTON', notes: 'FUNCTIONAL'),
    HistoricalRecord(deskId: 'LAB6 - PC5', category: 'SSD', dntsSerial: 'L6-D05-SSD', mfgSerial: '50026B727302C6EA', brand: 'KINGSTON', notes: 'FUNCTIONAL'),
    HistoricalRecord(deskId: 'LAB6 - PC6', category: 'SSD', dntsSerial: 'L6-D06-SSD', mfgSerial: '50026B727302C6A6', brand: 'KINGSTON', notes: 'FUNCTIONAL'),
    HistoricalRecord(deskId: 'LAB6 - PC7', category: 'SSD', dntsSerial: 'L6-D07-SSD', mfgSerial: '50026B727302C6E5', brand: 'KINGSTON', notes: 'FUNCTIONAL'),
    HistoricalRecord(deskId: 'LAB6 - PC8', category: 'SSD', dntsSerial: 'L6-D08-SSD', mfgSerial: '50026B7273019BFC', brand: 'KINGSTON', notes: 'FUNCTIONAL'),
    HistoricalRecord(deskId: 'LAB6 - PC9', category: 'SSD', dntsSerial: 'L6-D09-SSD', mfgSerial: '50026B727302C6E7', brand: 'KINGSTON', notes: 'FUNCTIONAL'),
    HistoricalRecord(deskId: 'LAB6 - PC10', category: 'SSD', dntsSerial: 'L6-D10-SSD', mfgSerial: '50026B727302C71D', brand: 'KINGSTON', notes: 'FUNCTIONAL'),
    HistoricalRecord(deskId: 'LAB6 - PC11', category: 'SSD', dntsSerial: 'L6-D11-SSD', mfgSerial: '50026B727302C72A', brand: 'KINGSTON', notes: 'FUNCTIONAL'),
    HistoricalRecord(deskId: 'LAB6 - PC12', category: 'SSD', dntsSerial: 'L6-D12-SSD', mfgSerial: '50026B727302C714', brand: 'KINGSTON', notes: 'FUNCTIONAL'),
    HistoricalRecord(deskId: 'LAB6 - PC13', category: 'SSD', dntsSerial: 'L6-D13-SSD', mfgSerial: '50026B727302CC76', brand: 'KINGSTON', notes: 'FUNCTIONAL'),
    HistoricalRecord(deskId: 'LAB6 - PC14', category: 'SSD', dntsSerial: 'L6-D14-SSD', mfgSerial: '50026B727302C71C', brand: 'KINGSTON', notes: 'FUNCTIONAL'),
    HistoricalRecord(deskId: 'LAB6 - PC15', category: 'SSD', dntsSerial: 'L6-D15-SSD', mfgSerial: '50026B727301A17D', brand: 'KINGSTON', notes: 'FUNCTIONAL'),
    HistoricalRecord(deskId: 'LAB6 - PC16', category: 'SSD', dntsSerial: 'L6-D16-SSD', mfgSerial: '50026B727302C6B1', brand: 'KINGSTON', notes: 'FUNCTIONAL'),
    HistoricalRecord(deskId: 'LAB6 - PC17', category: 'SSD', dntsSerial: 'L6-D17-SSD', mfgSerial: '50026B727302C7CC', brand: 'KINGSTON', notes: 'FUNCTIONAL'),
    HistoricalRecord(deskId: 'LAB6 - PC18', category: 'SSD', dntsSerial: 'L6-D18-SSD', mfgSerial: '50026B727302C671', brand: 'KINGSTON', notes: 'FUNCTIONAL'),
    HistoricalRecord(deskId: 'LAB6 - PC19', category: 'SSD', dntsSerial: 'L6-D19-SSD', mfgSerial: '50026B727302CC7A', brand: 'KINGSTON', notes: 'FUNCTIONAL'),
    HistoricalRecord(deskId: 'LAB6 - PC20', category: 'SSD', dntsSerial: 'L6-D20-SSD', mfgSerial: '50026B727302CCB5', brand: 'KINGSTON', notes: 'FUNCTIONAL'),
    HistoricalRecord(deskId: 'LAB6 - PC21', category: 'SSD', dntsSerial: 'L6-D21-SSD', mfgSerial: '50026B727302C2B0', brand: 'KINGSTON', notes: 'FUNCTIONAL'),
    HistoricalRecord(deskId: 'LAB6 - PC22', category: 'SSD', dntsSerial: 'L6-D22-SSD', mfgSerial: '50026B727302CB45', brand: 'KINGSTON', notes: 'FUNCTIONAL'),
    HistoricalRecord(deskId: 'LAB6 - PC23', category: 'SSD', dntsSerial: 'L6-D23-SSD', mfgSerial: '50026B727302C67B', brand: 'KINGSTON', notes: 'FUNCTIONAL'),
    HistoricalRecord(deskId: 'LAB6 - PC24', category: 'SSD', dntsSerial: 'L6-D24-SSD', mfgSerial: '50026B727302C2A7', brand: 'KINGSTON', notes: 'FUNCTIONAL'),
    HistoricalRecord(deskId: 'LAB6 - PC25', category: 'SSD', dntsSerial: 'L6-D25-SSD', mfgSerial: '50026B72730276B4', brand: 'KINGSTON', notes: 'FUNCTIONAL'),
    HistoricalRecord(deskId: 'LAB6 - PC26', category: 'SSD', dntsSerial: 'L6-D26-SSD', mfgSerial: '50026B727302C6F4', brand: 'KINGSTON', notes: 'FUNCTIONAL'),
    HistoricalRecord(deskId: 'LAB6 - PC27', category: 'SSD', dntsSerial: 'L6-D27-SSD', mfgSerial: '50026B727301A17F', brand: 'KINGSTON', notes: 'FUNCTIONAL'),
    HistoricalRecord(deskId: 'LAB6 - PC28', category: 'SSD', dntsSerial: 'L6-D28-SSD', mfgSerial: '50026B727302C691', brand: 'KINGSTON', notes: 'FUNCTIONAL'),
    HistoricalRecord(deskId: 'LAB6 - PC29', category: 'SSD', dntsSerial: 'L6-D29-SSD', mfgSerial: '50026B727301A198', brand: 'KINGSTON', notes: 'FUNCTIONAL'),
    HistoricalRecord(deskId: 'LAB6 - PC30', category: 'SSD', dntsSerial: 'L6-D30-SSD', mfgSerial: '50026B727302C676', brand: 'KINGSTON', notes: 'FUNCTIONAL'),
    HistoricalRecord(deskId: 'LAB6 - PC31', category: 'SSD', dntsSerial: 'L6-D31-SSD', mfgSerial: '50026B727302C6A8', brand: 'KINGSTON', notes: 'FUNCTIONAL'),
    HistoricalRecord(deskId: 'LAB6 - PC32', category: 'SSD', dntsSerial: 'L6-D32-SSD', mfgSerial: '50026B727302C417', brand: 'KINGSTON', notes: 'FUNCTIONAL'),
    HistoricalRecord(deskId: 'LAB6 - PC33', category: 'SSD', dntsSerial: 'L6-D33-SSD', mfgSerial: '50026B727302C7F5', brand: 'KINGSTON', notes: 'FUNCTIONAL'),
    HistoricalRecord(deskId: 'LAB6 - PC34', category: 'SSD', dntsSerial: 'L6-D34-SSD', mfgSerial: '50026B727302C731', brand: 'KINGSTON', notes: 'FUNCTIONAL'),
    HistoricalRecord(deskId: 'LAB6 - PC35', category: 'SSD', dntsSerial: 'L6-D35-SSD', mfgSerial: '50026B727302C696', brand: 'KINGSTON', notes: 'FUNCTIONAL'),
    HistoricalRecord(deskId: 'LAB6 - PC36', category: 'SSD', dntsSerial: 'L6-D36-SSD', mfgSerial: '50026B727302C697', brand: 'KINGSTON', notes: 'FUNCTIONAL'),
    HistoricalRecord(deskId: 'LAB6 - PC37', category: 'SSD', dntsSerial: 'L6-D37-SSD', mfgSerial: '50026B7273019C13', brand: 'KINGSTON', notes: 'FUNCTIONAL'),
    HistoricalRecord(deskId: 'LAB6 - PC38', category: 'SSD', dntsSerial: 'L6-D38-SSD', mfgSerial: '50026B727302C6BE', brand: 'KINGSTON', notes: 'FUNCTIONAL'),
    HistoricalRecord(deskId: 'LAB6 - PC39', category: 'SSD', dntsSerial: 'L6-D39-SSD', mfgSerial: '50026B727301A19D', brand: 'KINGSTON', notes: 'FUNCTIONAL'),
    HistoricalRecord(deskId: 'LAB6 - PC40', category: 'SSD', dntsSerial: 'L6-D40-SSD', mfgSerial: '50026B727302CC91', brand: 'KINGSTON', notes: 'FUNCTIONAL'),
    HistoricalRecord(deskId: 'LAB6 - PC41', category: 'SSD', dntsSerial: 'L6-D41-SSD', mfgSerial: '0025_3386_91BD_9339', brand: 'SAMSUNG', notes: 'ACCOUNTING - FUNCTIONAL'),
    HistoricalRecord(deskId: 'LAB6 - PC42', category: 'SSD', dntsSerial: 'L6-D42-SSD', mfgSerial: '0025_3386_91BD_93B2', brand: 'SAMSUNG', notes: 'ACCOUNTING - FUNCTIONAL'),
    HistoricalRecord(deskId: 'LAB6 - PC43', category: 'SSD', dntsSerial: 'L6-D43-SSD', mfgSerial: '0025_3386_91BD_93F4', brand: 'SAMSUNG', notes: 'ACCOUNTING - FUNCTIONAL'),
    HistoricalRecord(deskId: 'LAB6 - PC44', category: 'SSD', dntsSerial: 'L6-D44-SSD', mfgSerial: '0025_3386_91BD_93F5', brand: 'SAMSUNG', notes: 'REGISTRAR - FUNCTIONAL'),
    HistoricalRecord(deskId: 'LAB6 - PC45', category: 'SSD', dntsSerial: 'L6-D45-SSD', mfgSerial: '0025_3386_91BD_93E1', brand: 'SAMSUNG', notes: 'ACCOUNTING - FUNCTIONAL'),
    HistoricalRecord(deskId: 'LAB6 - PC46', category: 'SSD', dntsSerial: 'L6-D46-SSD', mfgSerial: '0025_3386_91BD_933EF', brand: 'SAMSUNG', notes: 'ID PROCESSING / PIT-OS - FUNCTIONAL'),
    HistoricalRecord(deskId: 'LAB6 - PC47', category: 'SSD', dntsSerial: 'L6-D47-SSD', mfgSerial: '0025_3386_91BD_9339', brand: 'SAMSUNG', notes: 'ACCOUNTING - FUNCTIONAL'),
    HistoricalRecord(deskId: 'LAB6 - PC48', category: 'SSD', dntsSerial: 'L6-D48-SSD', mfgSerial: '0025_3386_91BD_93B5', brand: 'SAMSUNG', notes: 'ACCOUNTING - FUNCTIONAL'),
  ];
}
