import 'historical_baseline_provider.dart';

class HistoricalDataLab6 {
  static const List<HistoricalRecord> lab6Data = [
    HistoricalRecord(
      deskId: 'L6_D01',
      category: 'SSD',
      dntsSerial: 'L6-D01-SSD',
      mfgSerial: '50026B727302C7E0',
      brand: 'KINGSTON',
      notes: 'NONE - FUNCTIONAL',
    ),
    HistoricalRecord(
      deskId: 'L6_D02',
      category: 'SSD',
      dntsSerial: 'L6-D02-SSD',
      mfgSerial: '50026B727302CCB4',
      brand: 'KINGSTON',
      notes: 'NONE - FUNCTIONAL',
    ),
    HistoricalRecord(
      deskId: 'L6_D03',
      category: 'SSD',
      dntsSerial: 'L6-D03-SSD',
      mfgSerial: '50026B727302C687',
      brand: 'KINGSTON',
      notes: 'NONE - FUNCTIONAL',
    ),
    HistoricalRecord(
      deskId: 'L6_D04',
      category: 'SSD',
      dntsSerial: 'L6-D04-SSD',
      mfgSerial: '50026B727302C6E2',
      brand: 'KINGSTON',
      notes: 'NONE - FUNCTIONAL',
    ),
    HistoricalRecord(
      deskId: 'L6_D05',
      category: 'SSD',
      dntsSerial: 'L6-D05-SSD',
      mfgSerial: '50026B727302C6EA',
      brand: 'KINGSTON',
      notes: 'NONE - FUNCTIONAL',
    ),
    HistoricalRecord(
      deskId: 'L6_D06',
      category: 'SSD',
      dntsSerial: 'L6-D06-SSD',
      mfgSerial: '50026B727302C6A6',
      brand: 'KINGSTON',
      notes: 'NONE - FUNCTIONAL',
    ),
    HistoricalRecord(
      deskId: 'L6_D07',
      category: 'SSD',
      dntsSerial: 'L6-D07-SSD',
      mfgSerial: '50026B727302C6E5',
      brand: 'KINGSTON',
      notes: 'NONE - FUNCTIONAL',
    ),
    HistoricalRecord(
      deskId: 'L6_D08',
      category: 'SSD',
      dntsSerial: 'L6-D08-SSD',
      mfgSerial: '50026B7273019BFC',
      brand: 'KINGSTON',
      notes: 'NONE - FUNCTIONAL',
    ),
    HistoricalRecord(
      deskId: 'L6_D09',
      category: 'SSD',
      dntsSerial: 'L6-D09-SSD',
      mfgSerial: '50026B727302C6E7',
      brand: 'KINGSTON',
      notes: 'NONE - FUNCTIONAL',
    ),
    HistoricalRecord(
      deskId: 'L6_D10',
      category: 'SSD',
      dntsSerial: 'L6-D10-SSD',
      mfgSerial: '50026B727302C71D',
      brand: 'KINGSTON',
      notes: 'NONE - FUNCTIONAL',
    ),
    HistoricalRecord(
      deskId: 'L6_D11',
      category: 'SSD',
      dntsSerial: 'L6-D11-SSD',
      mfgSerial: '50026B727302C72A',
      brand: 'KINGSTON',
      notes: 'NONE - FUNCTIONAL',
    ),
    HistoricalRecord(
      deskId: 'L6_D12',
      category: 'SSD',
      dntsSerial: 'L6-D12-SSD',
      mfgSerial: '50026B727302C714',
      brand: 'KINGSTON',
      notes: 'NONE - FUNCTIONAL',
    ),
    HistoricalRecord(
      deskId: 'L6_D13',
      category: 'SSD',
      dntsSerial: 'L6-D13-SSD',
      mfgSerial: '50026B727302CC76',
      brand: 'KINGSTON',
      notes: 'NONE - FUNCTIONAL',
    ),
    HistoricalRecord(
      deskId: 'L6_D14',
      category: 'SSD',
      dntsSerial: 'L6-D14-SSD',
      mfgSerial: '50026B727302C71C',
      brand: 'KINGSTON',
      notes: 'NONE - FUNCTIONAL',
    ),
    HistoricalRecord(
      deskId: 'L6_D15',
      category: 'SSD',
      dntsSerial: 'L6-D15-SSD',
      mfgSerial: '50026B727301A17D',
      brand: 'KINGSTON',
      notes: 'NONE - FUNCTIONAL',
    ),
    HistoricalRecord(
      deskId: 'L6_D16',
      category: 'SSD',
      dntsSerial: 'L6-D16-SSD',
      mfgSerial: '50026B727302C6B1',
      brand: 'KINGSTON',
      notes: 'NONE - FUNCTIONAL',
    ),
    HistoricalRecord(
      deskId: 'L6_D17',
      category: 'SSD',
      dntsSerial: 'L6-D17-SSD',
      mfgSerial: '50026B727302C7CC',
      brand: 'KINGSTON',
      notes: 'NONE - FUNCTIONAL',
    ),
    HistoricalRecord(
      deskId: 'L6_D18',
      category: 'SSD',
      dntsSerial: 'L6-D18-SSD',
      mfgSerial: '50026B727302C671',
      brand: 'KINGSTON',
      notes: 'NONE - FUNCTIONAL',
    ),
    HistoricalRecord(
      deskId: 'L6_D19',
      category: 'SSD',
      dntsSerial: 'L6-D19-SSD',
      mfgSerial: '50026B727302CC7A',
      brand: 'KINGSTON',
      notes: 'NONE - FUNCTIONAL',
    ),
    HistoricalRecord(
      deskId: 'L6_D20',
      category: 'SSD',
      dntsSerial: 'L6-D20-SSD',
      mfgSerial: '50026B727302CCB5',
      brand: 'KINGSTON',
      notes: 'NONE - FUNCTIONAL',
    ),
    HistoricalRecord(
      deskId: 'L6_D21',
      category: 'SSD',
      dntsSerial: 'L6-D21-SSD',
      mfgSerial: '50026B727302C2B0',
      brand: 'KINGSTON',
      notes: 'NONE - FUNCTIONAL',
    ),
    HistoricalRecord(
      deskId: 'L6_D22',
      category: 'SSD',
      dntsSerial: 'L6-D22-SSD',
      mfgSerial: '50026B727302CB45',
      brand: 'KINGSTON',
      notes: 'NONE - FUNCTIONAL',
    ),
    HistoricalRecord(
      deskId: 'L6_D23',
      category: 'SSD',
      dntsSerial: 'L6-D23-SSD',
      mfgSerial: '50026B727302C67B',
      brand: 'KINGSTON',
      notes: 'NONE - FUNCTIONAL',
    ),
    HistoricalRecord(
      deskId: 'L6_D24',
      category: 'SSD',
      dntsSerial: 'L6-D24-SSD',
      mfgSerial: '50026B727302C2A7',
      brand: 'KINGSTON',
      notes: 'NONE - FUNCTIONAL',
    ),
    HistoricalRecord(
      deskId: 'L6_D25',
      category: 'SSD',
      dntsSerial: 'L6-D25-SSD',
      mfgSerial: '50026B72730276B4',
      brand: 'KINGSTON',
      notes: 'NONE - FUNCTIONAL',
    ),
    HistoricalRecord(
      deskId: 'L6_D26',
      category: 'SSD',
      dntsSerial: 'L6-D26-SSD',
      mfgSerial: '50026B727302C6F4',
      brand: 'KINGSTON',
      notes: 'NONE - FUNCTIONAL',
    ),
    HistoricalRecord(
      deskId: 'L6_D27',
      category: 'SSD',
      dntsSerial: 'L6-D27-SSD',
      mfgSerial: '50026B727301A17F',
      brand: 'KINGSTON',
      notes: 'NONE - FUNCTIONAL',
    ),
    HistoricalRecord(
      deskId: 'L6_D28',
      category: 'SSD',
      dntsSerial: 'L6-D28-SSD',
      mfgSerial: '50026B727302C691',
      brand: 'KINGSTON',
      notes: 'NONE - FUNCTIONAL',
    ),
    HistoricalRecord(
      deskId: 'L6_D29',
      category: 'SSD',
      dntsSerial: 'L6-D29-SSD',
      mfgSerial: '50026B727301A198',
      brand: 'KINGSTON',
      notes: 'NONE - FUNCTIONAL',
    ),
    HistoricalRecord(
      deskId: 'L6_D30',
      category: 'SSD',
      dntsSerial: 'L6-D30-SSD',
      mfgSerial: '50026B727302C676',
      brand: 'KINGSTON',
      notes: 'NONE - FUNCTIONAL',
    ),
    HistoricalRecord(
      deskId: 'L6_D31',
      category: 'SSD',
      dntsSerial: 'L6-D31-SSD',
      mfgSerial: '50026B727302C6A8',
      brand: 'KINGSTON',
      notes: 'NONE - FUNCTIONAL',
    ),
    HistoricalRecord(
      deskId: 'L6_D32',
      category: 'SSD',
      dntsSerial: 'L6-D32-SSD',
      mfgSerial: '50026B727302C417',
      brand: 'KINGSTON',
      notes: 'NONE - FUNCTIONAL',
    ),
    HistoricalRecord(
      deskId: 'L6_D33',
      category: 'SSD',
      dntsSerial: 'L6-D33-SSD',
      mfgSerial: '50026B727302C7F5',
      brand: 'KINGSTON',
      notes: 'NONE - FUNCTIONAL',
    ),
    HistoricalRecord(
      deskId: 'L6_D34',
      category: 'SSD',
      dntsSerial: 'L6-D34-SSD',
      mfgSerial: '50026B727302C731',
      brand: 'KINGSTON',
      notes: 'NONE - FUNCTIONAL',
    ),
    HistoricalRecord(
      deskId: 'L6_D35',
      category: 'SSD',
      dntsSerial: 'L6-D35-SSD',
      mfgSerial: '50026B727302C696',
      brand: 'KINGSTON',
      notes: 'NONE - FUNCTIONAL',
    ),
    HistoricalRecord(
      deskId: 'L6_D36',
      category: 'SSD',
      dntsSerial: 'L6-D36-SSD',
      mfgSerial: '50026B727302C697',
      brand: 'KINGSTON',
      notes: 'NONE - FUNCTIONAL',
    ),
    HistoricalRecord(
      deskId: 'L6_D37',
      category: 'SSD',
      dntsSerial: 'L6-D37-SSD',
      mfgSerial: '50026B7273019C13',
      brand: 'KINGSTON',
      notes: 'NONE - FUNCTIONAL',
    ),
    HistoricalRecord(
      deskId: 'L6_D38',
      category: 'SSD',
      dntsSerial: 'L6-D38-SSD',
      mfgSerial: '50026B727302C6BE',
      brand: 'KINGSTON',
      notes: 'NONE - FUNCTIONAL',
    ),
    HistoricalRecord(
      deskId: 'L6_D39',
      category: 'SSD',
      dntsSerial: 'L6-D39-SSD',
      mfgSerial: '50026B727301A19D',
      brand: 'KINGSTON',
      notes: 'NONE - FUNCTIONAL',
    ),
    HistoricalRecord(
      deskId: 'L6_D40',
      category: 'SSD',
      dntsSerial: 'L6-D40-SSD',
      mfgSerial: '50026B727302CC91',
      brand: 'KINGSTON',
      notes: 'NONE - FUNCTIONAL',
    ),
    HistoricalRecord(
      deskId: 'L6_D41',
      category: 'SSD',
      dntsSerial: 'L6-D41-SSD',
      mfgSerial: '0025_3386_91BD_9339',
      brand: 'SAMSUNG',
      notes: 'ACCOUNTING - FUNCTIONAL',
    ),
    HistoricalRecord(
      deskId: 'L6_D42',
      category: 'SSD',
      dntsSerial: 'L6-D42-SSD',
      mfgSerial: '0025_3386_91BD_93B2',
      brand: 'SAMSUNG',
      notes: 'ACCOUNTING - FUNCTIONAL',
    ),
    HistoricalRecord(
      deskId: 'L6_D43',
      category: 'SSD',
      dntsSerial: 'L6-D43-SSD',
      mfgSerial: '0025_3386_91BD_93F4',
      brand: 'SAMSUNG',
      notes: 'ACCOUNTING - FUNCTIONAL',
    ),
    HistoricalRecord(
      deskId: 'L6_D44',
      category: 'SSD',
      dntsSerial: 'L6-D44-SSD',
      mfgSerial: '0025_3386_91BD_93F5',
      brand: 'SAMSUNG',
      notes: 'REGISTRAR - FUNCTIONAL',
    ),
    HistoricalRecord(
      deskId: 'L6_D45',
      category: 'SSD',
      dntsSerial: 'L6-D45-SSD',
      mfgSerial: '0025_3386_91BD_93E1',
      brand: 'SAMSUNG',
      notes: 'ACCOUNTING - FUNCTIONAL',
    ),
    HistoricalRecord(
      deskId: 'L6_D46',
      category: 'SSD',
      dntsSerial: 'L6-D46-SSD',
      mfgSerial: '0025_3386_91BD_933EF',
      brand: 'SAMSUNG',
      notes: 'ID PROCESSING / PIT-OS - FUNCTIONAL',
    ),
    HistoricalRecord(
      deskId: 'L6_D47',
      category: 'SSD',
      dntsSerial: 'L6-D47-SSD',
      mfgSerial: '0025_3386_91BD_9339',
      brand: 'SAMSUNG',
      notes: 'ACCOUNTING - FUNCTIONAL',
    ),
    HistoricalRecord(
      deskId: 'L6_D48',
      category: 'SSD',
      dntsSerial: 'L6-D48-SSD',
      mfgSerial: '0025_3386_91BD_93B5',
      brand: 'SAMSUNG',
      notes: 'ACCOUNTING - FUNCTIONAL',
    ),
  ];
}
