import 'historical_baseline_provider.dart';

class HistoricalDataLab7 {
  static const List<HistoricalRecord> lab7Data = [
    // ═══════════════════════════════════════════════════════════════════════════
    // MONITORS (DUAL SETUP: MRL & MRR)
    // ═══════════════════════════════════════════════════════════════════════════
    // PC1
    HistoricalRecord(deskId: 'LAB7 - PC1', category: 'MONITOR', brand: 'SAMSUNG', mfgSerial: 'ZZNNH4ZM501120J', dntsSerial: 'L7-MRL-01', notes: 'LEFT - FUNCTIONAL'),
    HistoricalRecord(deskId: 'LAB7 - PC1', category: 'MONITOR', brand: 'SAMSUNG', mfgSerial: 'ZZNNH4ZM500808W', dntsSerial: 'L7-MRR-01', notes: 'RIGHT - FUNCTIONAL'),
    // PC2
    HistoricalRecord(deskId: 'LAB7 - PC2', category: 'MONITOR', brand: 'SAMSUNG', mfgSerial: 'ZZNNH4ZM300156Z', dntsSerial: 'L7-MRL-02', notes: 'LEFT - FUNCTIONAL'),
    HistoricalRecord(deskId: 'LAB7 - PC2', category: 'MONITOR', brand: 'SAMSUNG', mfgSerial: 'ZZNNH4ZM502217R', dntsSerial: 'L7-MRR-02', notes: 'RIGHT - FUNCTIONAL'),
    // PC3
    HistoricalRecord(deskId: 'LAB7 - PC3', category: 'MONITOR', brand: 'SAMSUNG', mfgSerial: 'ZZNNH4ZM501199B', dntsSerial: 'L7-MRL-03', notes: 'LEFT - FUNCTIONAL'),
    HistoricalRecord(deskId: 'LAB7 - PC3', category: 'MONITOR', brand: 'SAMSUNG', mfgSerial: 'ZZNNH4ZM502562V', dntsSerial: 'L7-MRR-03', notes: 'RIGHT - FUNCTIONAL'),
    // PC4
    HistoricalRecord(deskId: 'LAB7 - PC4', category: 'MONITOR', brand: 'SAMSUNG', mfgSerial: 'ZZNNH4ZM501839R', dntsSerial: 'L7-MRL-04', notes: 'LEFT - FUNCTIONAL'),
    HistoricalRecord(deskId: 'LAB7 - PC4', category: 'MONITOR', brand: 'SAMSUNG', mfgSerial: 'ZZNNH4ZM105798R', dntsSerial: 'L7-MRR-04', notes: 'RIGHT - FUNCTIONAL'),
    // PC5
    HistoricalRecord(deskId: 'LAB7 - PC5', category: 'MONITOR', brand: 'SAMSUNG', mfgSerial: 'ZZNNH4ZM701914D', dntsSerial: 'L7-MRL-05', notes: 'LEFT - FUNCTIONAL'),
    HistoricalRecord(deskId: 'LAB7 - PC5', category: 'MONITOR', brand: 'SAMSUNG', mfgSerial: 'ZZNNH4ZM500534L', dntsSerial: 'L7-MRR-05', notes: 'RIGHT - FUNCTIONAL'),
    // PC6
    HistoricalRecord(deskId: 'LAB7 - PC6', category: 'MONITOR', brand: 'SAMSUNG', mfgSerial: 'ZZNNH4ZM703346H', dntsSerial: 'L7-MRL-06', notes: 'LEFT - FUNCTIONAL'),
    HistoricalRecord(deskId: 'LAB7 - PC6', category: 'MONITOR', brand: 'SAMSUNG', mfgSerial: 'ZZNNH4ZM502625F', dntsSerial: 'L7-MRR-06', notes: 'RIGHT - FUNCTIONAL'),
    // PC7
    HistoricalRecord(deskId: 'LAB7 - PC7', category: 'MONITOR', brand: 'SAMSUNG', mfgSerial: 'ZZNNH4ZM502538T', dntsSerial: 'L7-MRL-07', notes: 'LEFT - FUNCTIONAL'),
    HistoricalRecord(deskId: 'LAB7 - PC7', category: 'MONITOR', brand: 'SAMSUNG', mfgSerial: 'ZZNNH4ZM500118D', dntsSerial: 'L7-MRR-07', notes: 'RIGHT - FUNCTIONAL'),
    // PC8
    HistoricalRecord(deskId: 'LAB7 - PC8', category: 'MONITOR', brand: 'SAMSUNG', mfgSerial: 'ZZNNH4ZM502282P', dntsSerial: 'L7-MRL-08', notes: 'LEFT - FUNCTIONAL'),
    HistoricalRecord(deskId: 'LAB7 - PC8', category: 'MONITOR', brand: 'SAMSUNG', mfgSerial: 'ZZNNH4ZM500775V', dntsSerial: 'L7-MRR-08', notes: 'RIGHT - FUNCTIONAL'),
    // PC9
    HistoricalRecord(deskId: 'LAB7 - PC9', category: 'MONITOR', brand: 'SAMSUNG', mfgSerial: 'ZZNNH4ZM501336P', dntsSerial: 'L7-MRL-09', notes: 'LEFT - FUNCTIONAL'),
    HistoricalRecord(deskId: 'LAB7 - PC9', category: 'MONITOR', brand: 'SAMSUNG', mfgSerial: 'ZZNNH4ZM500446V', dntsSerial: 'L7-MRR-09', notes: 'RIGHT - FUNCTIONAL'),
    // PC10
    HistoricalRecord(deskId: 'LAB7 - PC10', category: 'MONITOR', brand: 'SAMSUNG', mfgSerial: 'ZZNNH4ZM301595T', dntsSerial: 'L7-MRL-10', notes: 'LEFT - FUNCTIONAL'),
    HistoricalRecord(deskId: 'LAB7 - PC10', category: 'MONITOR', brand: 'SAMSUNG', mfgSerial: 'ZZNNH4ZM300433B', dntsSerial: 'L7-MRR-10', notes: 'RIGHT - FUNCTIONAL'),
    // PC11
    HistoricalRecord(deskId: 'LAB7 - PC11', category: 'MONITOR', brand: 'SAMSUNG', mfgSerial: 'ZZNNH4ZM105624E', dntsSerial: 'L7-MRL-11', notes: 'LEFT - FUNCTIONAL'),
    HistoricalRecord(deskId: 'LAB7 - PC11', category: 'MONITOR', brand: 'SAMSUNG', mfgSerial: 'ZZNNH4ZM501517M', dntsSerial: 'L7-MRR-11', notes: 'RIGHT - FUNCTIONAL'),
    // PC12
    HistoricalRecord(deskId: 'LAB7 - PC12', category: 'MONITOR', brand: 'SAMSUNG', mfgSerial: 'ZZNH4ZM602328K', dntsSerial: 'L7-MRL-12', notes: 'LEFT - FUNCTIONAL'),
    HistoricalRecord(deskId: 'LAB7 - PC12', category: 'MONITOR', brand: 'SAMSUNG', mfgSerial: 'ZZNNH4ZM501945V', dntsSerial: 'L7-MRR-12', notes: 'RIGHT - FUNCTIONAL'),
    // PC13
    HistoricalRecord(deskId: 'LAB7 - PC13', category: 'MONITOR', brand: 'SAMSUNG', mfgSerial: 'ZZNNH4ZM500800B', dntsSerial: 'L7-MRL-13', notes: 'LEFT - FUNCTIONAL'),
    HistoricalRecord(deskId: 'LAB7 - PC13', category: 'MONITOR', brand: 'SAMSUNG', mfgSerial: 'ZZNNH4ZM500233J', dntsSerial: 'L7-MRR-13', notes: 'RIGHT - FUNCTIONAL'),
    // PC14
    HistoricalRecord(deskId: 'LAB7 - PC14', category: 'MONITOR', brand: 'SAMSUNG', mfgSerial: 'ZZNNH4ZM501074L', dntsSerial: 'L7-MRL-14', notes: 'LEFT - FUNCTIONAL'),
    HistoricalRecord(deskId: 'LAB7 - PC14', category: 'MONITOR', brand: 'SAMSUNG', mfgSerial: 'ZZNNH4ZM500393R', dntsSerial: 'L7-MRR-14', notes: 'RIGHT - FUNCTIONAL'),
    // PC15
    HistoricalRecord(deskId: 'LAB7 - PC15', category: 'MONITOR', brand: 'SAMSUNG', mfgSerial: 'ZZNNH4ZM502115K', dntsSerial: 'L7-MRL-15', notes: 'LEFT - FUNCTIONAL'),
    HistoricalRecord(deskId: 'LAB7 - PC15', category: 'MONITOR', brand: 'SAMSUNG', mfgSerial: 'ZZNNH4ZM500190Y', dntsSerial: 'L7-MRR-15', notes: 'RIGHT - FUNCTIONAL'),
    // PC16
    HistoricalRecord(deskId: 'LAB7 - PC16', category: 'MONITOR', brand: 'SAMSUNG', mfgSerial: 'ZZNNH4ZM501698N', dntsSerial: 'L7-MRL-16', notes: 'LEFT - FUNCTIONAL'),
    HistoricalRecord(deskId: 'LAB7 - PC16', category: 'MONITOR', brand: 'SAMSUNG', mfgSerial: 'ZZNNH4ZM500966L', dntsSerial: 'L7-MRR-16', notes: 'RIGHT - FUNCTIONAL'),
    // PC17
    HistoricalRecord(deskId: 'LAB7 - PC17', category: 'MONITOR', brand: 'SAMSUNG', mfgSerial: 'ZZNNH4ZM500611L', dntsSerial: 'L7-MRL-17', notes: 'LEFT - FUNCTIONAL'),
    HistoricalRecord(deskId: 'LAB7 - PC17', category: 'MONITOR', brand: 'SAMSUNG', mfgSerial: 'ZZNNH4ZM501990X', dntsSerial: 'L7-MRR-17', notes: 'RIGHT - FUNCTIONAL'),
    // PC18
    HistoricalRecord(deskId: 'LAB7 - PC18', category: 'MONITOR', brand: 'SAMSUNG', mfgSerial: 'ZZNNH4ZM79302P', dntsSerial: 'L7-MRL-18', notes: 'LEFT - FUNCTIONAL'),
    HistoricalRecord(deskId: 'LAB7 - PC18', category: 'MONITOR', brand: 'SAMSUNG', mfgSerial: 'ZZNNH4ZM500525W', dntsSerial: 'L7-MRR-18', notes: 'RIGHT - FUNCTIONAL'),
    // PC19
    HistoricalRecord(deskId: 'LAB7 - PC19', category: 'MONITOR', brand: 'SAMSUNG', mfgSerial: 'ZZNNH4ZM502184H', dntsSerial: 'L7-MRL-19', notes: 'LEFT - FUNCTIONAL'),
    HistoricalRecord(deskId: 'LAB7 - PC19', category: 'MONITOR', brand: 'SAMSUNG', mfgSerial: 'ZZNNH4ZM501801K', dntsSerial: 'L7-MRR-19', notes: 'RIGHT - FUNCTIONAL'),
    // PC20
    HistoricalRecord(deskId: 'LAB7 - PC20', category: 'MONITOR', brand: 'SAMSUNG', mfgSerial: 'ZZNNH4ZM5011232', dntsSerial: 'L7-MRL-20', notes: 'LEFT - FUNCTIONAL'),
    HistoricalRecord(deskId: 'LAB7 - PC20', category: 'MONITOR', brand: 'SAMSUNG', mfgSerial: 'ZZNNH4ZM302001R', dntsSerial: 'L7-MRR-20', notes: 'RIGHT - FUNCTIONAL'),
    // PC21
    HistoricalRecord(deskId: 'LAB7 - PC21', category: 'MONITOR', brand: 'SAMSUNG', mfgSerial: 'ZZNNH4ZM500809P', dntsSerial: 'L7-MRL-21', notes: 'LEFT - FUNCTIONAL'),
    HistoricalRecord(deskId: 'LAB7 - PC21', category: 'MONITOR', brand: 'SAMSUNG', mfgSerial: 'ZZNNH4ZM501792V', dntsSerial: 'L7-MRR-21', notes: 'RIGHT - FUNCTIONAL'),
    // PC22
    HistoricalRecord(deskId: 'LAB7 - PC22', category: 'MONITOR', brand: 'SAMSUNG', mfgSerial: 'ZZNNH4ZM500508K', dntsSerial: 'L7-MRL-22', notes: 'LEFT - FUNCTIONAL'),
    HistoricalRecord(deskId: 'LAB7 - PC22', category: 'MONITOR', brand: 'SAMSUNG', mfgSerial: 'ZZNNH4ZM500386R', dntsSerial: 'L7-MRR-22', notes: 'RIGHT - FUNCTIONAL'),
    // PC23
    HistoricalRecord(deskId: 'LAB7 - PC23', category: 'MONITOR', brand: 'SAMSUNG', mfgSerial: 'ZZNNH4ZM300637H', dntsSerial: 'L7-MRL-23', notes: 'LEFT - FUNCTIONAL'),
    HistoricalRecord(deskId: 'LAB7 - PC23', category: 'MONITOR', brand: 'SAMSUNG', mfgSerial: 'ZZNNH4ZM700003', dntsSerial: 'L7-MRR-23', notes: 'RIGHT - FUNCTIONAL'),
    // PC24
    HistoricalRecord(deskId: 'LAB7 - PC24', category: 'MONITOR', brand: 'SAMSUNG', mfgSerial: 'ZZNNH4ZM500153P', dntsSerial: 'L7-MRL-24', notes: 'LEFT - FUNCTIONAL'),
    HistoricalRecord(deskId: 'LAB7 - PC24', category: 'MONITOR', brand: 'SAMSUNG', mfgSerial: 'ZZNNH4ZM502005L', dntsSerial: 'L7-MRR-24', notes: 'RIGHT - FUNCTIONAL'),
    // PC25
    HistoricalRecord(deskId: 'LAB7 - PC25', category: 'MONITOR', brand: 'SAMSUNG', mfgSerial: 'ZZNNH4ZM502597T', dntsSerial: 'L7-MRL-25', notes: 'LEFT - FUNCTIONAL'),
    HistoricalRecord(deskId: 'LAB7 - PC25', category: 'MONITOR', brand: 'SAMSUNG', mfgSerial: 'ZZNNH4ZM501194H', dntsSerial: 'L7-MRR-25', notes: 'RIGHT - FUNCTIONAL'),
    // PC26
    HistoricalRecord(deskId: 'LAB7 - PC26', category: 'MONITOR', brand: 'SAMSUNG', mfgSerial: 'ZZNNH4ZM502312W', dntsSerial: 'L7-MRL-26', notes: 'LEFT - FUNCTIONAL'),
    HistoricalRecord(deskId: 'LAB7 - PC26', category: 'MONITOR', brand: 'SAMSUNG', mfgSerial: 'ZZNNH4ZM500109A', dntsSerial: 'L7-MRR-26', notes: 'RIGHT - FUNCTIONAL'),
    // PC27
    HistoricalRecord(deskId: 'LAB7 - PC27', category: 'MONITOR', brand: 'SAMSUNG', mfgSerial: 'ZZNNH4ZM201802B', dntsSerial: 'L7-MRL-27', notes: 'LEFT - FUNCTIONAL'),
    HistoricalRecord(deskId: 'LAB7 - PC27', category: 'MONITOR', brand: 'SAMSUNG', mfgSerial: 'ZZNNH4ZM303265Y', dntsSerial: 'L7-MRR-27', notes: 'RIGHT - FUNCTIONAL'),
    // PC28
    HistoricalRecord(deskId: 'LAB7 - PC28', category: 'MONITOR', brand: 'SAMSUNG', mfgSerial: 'ZZNNH4ZM500137B', dntsSerial: 'L7-MRL-28', notes: 'LEFT - FUNCTIONAL'),
    HistoricalRecord(deskId: 'LAB7 - PC28', category: 'MONITOR', brand: 'SAMSUNG', mfgSerial: 'ZZNNH4ZM501467K', dntsSerial: 'L7-MRR-28', notes: 'RIGHT - FUNCTIONAL'),
    // PC29
    HistoricalRecord(deskId: 'LAB7 - PC29', category: 'MONITOR', brand: 'SAMSUNG', mfgSerial: 'ZZNNH4ZM500502A', dntsSerial: 'L7-MRL-29', notes: 'LEFT - FUNCTIONAL'),
    HistoricalRecord(deskId: 'LAB7 - PC29', category: 'MONITOR', brand: 'SAMSUNG', mfgSerial: 'ZZNNH4ZM500657K', dntsSerial: 'L7-MRR-29', notes: 'RIGHT - FUNCTIONAL'),
    // PC30
    HistoricalRecord(deskId: 'LAB7 - PC30', category: 'MONITOR', brand: 'SAMSUNG', mfgSerial: 'ZZNNH4ZM702786Z', dntsSerial: 'L7-MRL-30', notes: 'LEFT - FUNCTIONAL'),
    HistoricalRecord(deskId: 'LAB7 - PC30', category: 'MONITOR', brand: 'SAMSUNG', mfgSerial: 'ZZNNH4ZM500003W', dntsSerial: 'L7-MRR-30', notes: 'RIGHT - FUNCTIONAL'),
    // PC31
    HistoricalRecord(deskId: 'LAB7 - PC31', category: 'MONITOR', brand: 'SAMSUNG', mfgSerial: 'ZZNNH4ZM502327M', dntsSerial: 'L7-MRL-31', notes: 'LEFT - FUNCTIONAL'),
    HistoricalRecord(deskId: 'LAB7 - PC31', category: 'MONITOR', brand: 'SAMSUNG', mfgSerial: 'ZZNNH4ZM500672V', dntsSerial: 'L7-MRR-31', notes: 'RIGHT - FUNCTIONAL'),
    // PC32
    HistoricalRecord(deskId: 'LAB7 - PC32', category: 'MONITOR', brand: 'SAMSUNG', mfgSerial: 'ZZNNH4ZM500662P', dntsSerial: 'L7-MRL-32', notes: 'LEFT - FUNCTIONAL'),
    HistoricalRecord(deskId: 'LAB7 - PC32', category: 'MONITOR', brand: 'SAMSUNG', mfgSerial: 'ZZNNH4ZM500377E', dntsSerial: 'L7-MRR-32', notes: 'RIGHT - FUNCTIONAL'),
    // PC33
    HistoricalRecord(deskId: 'LAB7 - PC33', category: 'MONITOR', brand: 'SAMSUNG', mfgSerial: 'ZZNNH4ZM501275F', dntsSerial: 'L7-MRL-33', notes: 'LEFT - FUNCTIONAL'),
    HistoricalRecord(deskId: 'LAB7 - PC33', category: 'MONITOR', brand: 'SAMSUNG', mfgSerial: 'ZZNNH4ZM302784Y', dntsSerial: 'L7-MRR-33', notes: 'RIGHT - FUNCTIONAL'),
    // PC34
    HistoricalRecord(deskId: 'LAB7 - PC34', category: 'MONITOR', brand: 'SAMSUNG', mfgSerial: 'ZZNNH4ZM500341L', dntsSerial: 'L7-MRL-34', notes: 'LEFT - FUNCTIONAL'),
    HistoricalRecord(deskId: 'LAB7 - PC34', category: 'MONITOR', brand: 'SAMSUNG', mfgSerial: 'ZZNNH4ZM800269P', dntsSerial: 'L7-MRR-34', notes: 'RIGHT - FUNCTIONAL'),
    // PC35-PC42 (Moved to Enrollment)
    HistoricalRecord(deskId: 'LAB7 - PC35', category: 'MONITOR', brand: 'SAMSUNG', mfgSerial: 'ZZNNH4ZM501390L', dntsSerial: 'L7-MRL-35', notes: 'SIR. ANDREW PATIGDAS (ENROLLMENT)'),
    HistoricalRecord(deskId: 'LAB7 - PC35', category: 'MONITOR', brand: 'SAMSUNG', mfgSerial: 'ZZNNH4ZM502477A', dntsSerial: 'L7-MRR-35', notes: 'SIR. ANDREW PATIGDAS (ENROLLMENT)'),
    HistoricalRecord(deskId: 'LAB7 - PC36', category: 'MONITOR', brand: 'SAMSUNG', mfgSerial: 'ZZNNH4ZM106509D', dntsSerial: 'L7-MRL-36', notes: 'SIR. ANDREW PATIGDAS (ENROLLMENT)'),
    HistoricalRecord(deskId: 'LAB7 - PC36', category: 'MONITOR', brand: 'SAMSUNG', mfgSerial: 'ZZNNH4ZM500431L', dntsSerial: 'L7-MRR-36', notes: 'SIR. ANDREW PATIGDAS (ENROLLMENT)'),
    HistoricalRecord(deskId: 'LAB7 - PC37', category: 'MONITOR', brand: 'SAMSUNG', mfgSerial: 'ZZNNH4ZM500468T', dntsSerial: 'L7-MRL-37', notes: 'SIR. ANDREW PATIGDAS (ENROLLMENT)'),
    HistoricalRecord(deskId: 'LAB7 - PC37', category: 'MONITOR', brand: 'SAMSUNG', mfgSerial: 'ZZNNH4ZM501084E', dntsSerial: 'L7-MRR-37', notes: 'SIR. ANDREW PATIGDAS (ENROLLMENT)'),
    HistoricalRecord(deskId: 'LAB7 - PC38', category: 'MONITOR', brand: 'SAMSUNG', mfgSerial: 'ZZNNH4ZM303919W', dntsSerial: 'L7-MRL-38', notes: 'SIR. ANDREW PATIGDAS (ENROLLMENT)'),
    HistoricalRecord(deskId: 'LAB7 - PC38', category: 'MONITOR', brand: 'SAMSUNG', mfgSerial: 'ZZNNH4ZM500533N', dntsSerial: 'L7-MRR-38', notes: 'SIR. ANDREW PATIGDAS (ENROLLMENT)'),
    HistoricalRecord(deskId: 'LAB7 - PC39', category: 'MONITOR', brand: 'SAMSUNG', mfgSerial: 'ZZNNH4ZM501161E', dntsSerial: 'L7-MRL-39', notes: 'SIR. ANDREW PATIGDAS (ENROLLMENT)'),
    HistoricalRecord(deskId: 'LAB7 - PC39', category: 'MONITOR', brand: 'SAMSUNG', mfgSerial: 'ZZNNH4ZM600305L', dntsSerial: 'L7-MRR-39', notes: 'SIR. ANDREW PATIGDAS (ENROLLMENT)'),
    HistoricalRecord(deskId: 'LAB7 - PC40', category: 'MONITOR', brand: 'SAMSUNG', mfgSerial: 'ZZNNH4ZM500797T', dntsSerial: 'L7-MRL-40', notes: 'SIR. ANDREW PATIGDAS (ENROLLMENT)'),
    HistoricalRecord(deskId: 'LAB7 - PC40', category: 'MONITOR', brand: 'SAMSUNG', mfgSerial: 'ZZNNH4ZM501452Z', dntsSerial: 'L7-MRR-40', notes: 'SIR. ANDREW PATIGDAS (ENROLLMENT)'),
    HistoricalRecord(deskId: 'LAB7 - PC41', category: 'MONITOR', brand: 'SAMSUNG', mfgSerial: 'ZZNNH4ZM502324D', dntsSerial: 'L7-MRL-41', notes: 'SIR. ANDREW PATIGDAS (ENROLLMENT)'),
    HistoricalRecord(deskId: 'LAB7 - PC41', category: 'MONITOR', brand: 'SAMSUNG', mfgSerial: 'ZZNNH4ZM501888B', dntsSerial: 'L7-MRR-41', notes: 'SIR. ANDREW PATIGDAS (ENROLLMENT)'),
    HistoricalRecord(deskId: 'LAB7 - PC42', category: 'MONITOR', brand: 'SAMSUNG', mfgSerial: 'ZZNNH4ZM304296H', dntsSerial: 'L7-MRL-42', notes: 'SIR. ANDREW PATIGDAS (ENROLLMENT)'),
    HistoricalRecord(deskId: 'LAB7 - PC42', category: 'MONITOR', brand: 'SAMSUNG', mfgSerial: 'ZZNNH4ZM102383R', dntsSerial: 'L7-MRR-42', notes: 'SIR. ANDREW PATIGDAS (ENROLLMENT)'),
    // PC43
    HistoricalRecord(deskId: 'LAB7 - PC43', category: 'MONITOR', brand: 'SAMSUNG', mfgSerial: 'ZZNNH4ZM501814K', dntsSerial: 'L7-MRL-43', notes: 'LEFT - FUNCTIONAL'),
    HistoricalRecord(deskId: 'LAB7 - PC43', category: 'MONITOR', brand: 'SAMSUNG', mfgSerial: 'ZZNNH4ZM501519J', dntsSerial: 'L7-MRR-43', notes: 'RIGHT - FUNCTIONAL'),
    // PC44-PC48 (Partial)
    HistoricalRecord(deskId: 'LAB7 - PC44', category: 'MONITOR', brand: 'SAMSUNG', mfgSerial: 'ZZNNH4ZM400492Z', dntsSerial: 'L7-MRR-44', notes: 'RIGHT ONLY'),
    HistoricalRecord(deskId: 'LAB7 - PC45', category: 'MONITOR', brand: 'SAMSUNG', mfgSerial: 'ZZNNH4ZM701940L', dntsSerial: 'L7-MRR-45', notes: 'RIGHT ONLY'),
    HistoricalRecord(deskId: 'LAB7 - PC46', category: 'MONITOR', brand: 'SAMSUNG', mfgSerial: 'ZZNNH4ZM501789L', dntsSerial: 'L7-MRR-46', notes: 'RIGHT ONLY'),
    HistoricalRecord(deskId: 'LAB7 - PC47', category: 'MONITOR', brand: 'SAMSUNG', mfgSerial: 'ZZNNH4ZM502480E', dntsSerial: 'L6-MRL-47', notes: 'RIGHT ONLY - MOVED FROM LAB 6'),
    HistoricalRecord(deskId: 'LAB7 - PC48', category: 'MONITOR', brand: 'SAMSUNG', mfgSerial: 'ZZNNH4ZM501089V', dntsSerial: 'L7-MRR-48', notes: 'RIGHT ONLY - MS. KRISLY (SCHOLARSHIP)'),

    // ═══════════════════════════════════════════════════════════════════════════
    // SYSTEM UNITS (Parsed previously)
    // ═══════════════════════════════════════════════════════════════════════════
    HistoricalRecord(deskId: 'LAB7 - PC1', category: 'SYSTEM UNIT', brand: 'LENOVO', mfgSerial: 'YL00H6RM', dntsSerial: 'L7 SU - 01', notes: 'Intel i5'),
    HistoricalRecord(deskId: 'LAB7 - PC2', category: 'SYSTEM UNIT', brand: 'LENOVO', mfgSerial: 'YL00H60G', dntsSerial: 'L7 SU - 02', notes: 'Intel i5'),
    HistoricalRecord(deskId: 'LAB7 - PC3', category: 'SYSTEM UNIT', brand: 'LENOVO', mfgSerial: 'YL00H6RK', dntsSerial: 'L7 SU - 03', notes: 'Intel i5'),
    HistoricalRecord(deskId: 'LAB7 - PC4', category: 'SYSTEM UNIT', brand: 'LENOVO', mfgSerial: 'YL00H6RJ', dntsSerial: 'L7 SU - 04', notes: 'Intel i5'),
    HistoricalRecord(deskId: 'LAB7 - PC5', category: 'SYSTEM UNIT', brand: 'LENOVO', mfgSerial: 'YL00H6RX', dntsSerial: 'L7 SU - 05', notes: 'Intel i5'),
    HistoricalRecord(deskId: 'LAB7 - PC6', category: 'SYSTEM UNIT', brand: 'LENOVO', mfgSerial: 'YL00H6SB', dntsSerial: 'L7 SU - 06', notes: 'Intel i5'),
    HistoricalRecord(deskId: 'LAB7 - PC7', category: 'SYSTEM UNIT', brand: 'LENOVO', mfgSerial: 'YL00H6R7', dntsSerial: 'L7 SU - 07', notes: 'Intel i5'),
    HistoricalRecord(deskId: 'LAB7 - PC8', category: 'SYSTEM UNIT', brand: 'LENOVO', mfgSerial: 'YL00H6QM', dntsSerial: 'L7 SU - 08', notes: 'Intel i5'),
    HistoricalRecord(deskId: 'LAB7 - PC9', category: 'SYSTEM UNIT', brand: 'LENOVO', mfgSerial: 'YL00H6SD', dntsSerial: 'L7 SU - 09', notes: 'Intel i5'),
    HistoricalRecord(deskId: 'LAB7 - PC10', category: 'SYSTEM UNIT', brand: 'LENOVO', mfgSerial: 'YL00H6R4', dntsSerial: 'L7 SU - 10', notes: 'Intel i5'),
    HistoricalRecord(deskId: 'LAB7 - PC11', category: 'SYSTEM UNIT', brand: 'LENOVO', mfgSerial: 'YL00H6R3', dntsSerial: 'L7 SU - 11', notes: 'Intel i5'),
    HistoricalRecord(deskId: 'LAB7 - PC12', category: 'SYSTEM UNIT', brand: 'LENOVO', mfgSerial: 'YL00H6RY', dntsSerial: 'L7 SU - 12', notes: 'Intel i5'),
    HistoricalRecord(deskId: 'LAB7 - PC13', category: 'SYSTEM UNIT', brand: 'LENOVO', mfgSerial: 'YL00H6S8', dntsSerial: 'L7 SU - 13', notes: 'Intel i5'),
    HistoricalRecord(deskId: 'LAB7 - PC14', category: 'SYSTEM UNIT', brand: 'LENOVO', mfgSerial: 'YL00H6S0', dntsSerial: 'L7 SU - 14', notes: 'Intel i5'),
    HistoricalRecord(deskId: 'LAB7 - PC15', category: 'SYSTEM UNIT', brand: 'LENOVO', mfgSerial: 'YL00H6QY', dntsSerial: 'L7 SU - 15', notes: 'Intel i5'),
    HistoricalRecord(deskId: 'LAB7 - PC16', category: 'SYSTEM UNIT', brand: 'LENOVO', mfgSerial: 'YL00H6RR', dntsSerial: 'L7 SU - 16', notes: 'Intel i5'),
    HistoricalRecord(deskId: 'LAB7 - PC17', category: 'SYSTEM UNIT', brand: 'LENOVO', mfgSerial: 'YL00H6RP', dntsSerial: 'L7 SU - 17', notes: 'Intel i5'),
    HistoricalRecord(deskId: 'LAB7 - PC18', category: 'SYSTEM UNIT', brand: 'LENOVO', mfgSerial: 'YL00H6RW', dntsSerial: 'L7 SU - 18', notes: 'Intel i5'),
    HistoricalRecord(deskId: 'LAB7 - PC19', category: 'SYSTEM UNIT', brand: 'LENOVO', mfgSerial: 'YL00H6QK', dntsSerial: 'L7 SU - 19', notes: 'Intel i5'),
    HistoricalRecord(deskId: 'LAB7 - PC20', category: 'SYSTEM UNIT', brand: 'LENOVO', mfgSerial: 'YL00H6QZ', dntsSerial: 'L7 SU - 20', notes: 'Intel i5'),
    HistoricalRecord(deskId: 'LAB7 - PC21', category: 'SYSTEM UNIT', brand: 'LENOVO', mfgSerial: 'YL00H6SA', dntsSerial: 'L7 SU - 21', notes: 'Intel i5'),
    HistoricalRecord(deskId: 'LAB7 - PC22', category: 'SYSTEM UNIT', brand: 'LENOVO', mfgSerial: 'YL00H6RT', dntsSerial: 'L7 SU - 22', notes: 'Intel i5'),
    HistoricalRecord(deskId: 'LAB7 - PC23', category: 'SYSTEM UNIT', brand: 'LENOVO', mfgSerial: 'YL00H6RF', dntsSerial: 'L7 SU - 23', notes: 'Intel i5'),
    HistoricalRecord(deskId: 'LAB7 - PC24', category: 'SYSTEM UNIT', brand: 'LENOVO', mfgSerial: 'YL00H6QL', dntsSerial: 'L7 SU - 24', notes: 'Intel i5'),
    HistoricalRecord(deskId: 'LAB7 - PC25', category: 'SYSTEM UNIT', brand: 'LENOVO', mfgSerial: 'YL00H6RZ', dntsSerial: 'L7 SU - 25', notes: 'Intel i5'),
    HistoricalRecord(deskId: 'LAB7 - PC26', category: 'SYSTEM UNIT', brand: 'LENOVO', mfgSerial: 'YL00H6S4', dntsSerial: 'L7 SU - 26', notes: 'Intel i5'),
    HistoricalRecord(deskId: 'LAB7 - PC27', category: 'SYSTEM UNIT', brand: 'LENOVO', mfgSerial: 'YL00H6QS', dntsSerial: 'L7 SU - 27', notes: 'Intel i5'),
    HistoricalRecord(deskId: 'LAB7 - PC28', category: 'SYSTEM UNIT', brand: 'LENOVO', mfgSerial: 'YL00H6QN', dntsSerial: 'L7 SU - 28', notes: 'Intel i5'),
    HistoricalRecord(deskId: 'LAB7 - PC29', category: 'SYSTEM UNIT', brand: 'LENOVO', mfgSerial: 'YL00H6S2', dntsSerial: 'L7 SU - 29', notes: 'Intel i5'),
    HistoricalRecord(deskId: 'LAB7 - PC30', category: 'SYSTEM UNIT', brand: 'LENOVO', mfgSerial: 'YL00H6QE', dntsSerial: 'L7 SU - 30', notes: 'Intel i5'),
    HistoricalRecord(deskId: 'LAB7 - PC31', category: 'SYSTEM UNIT', brand: 'LENOVO', mfgSerial: 'YL00H6S7', dntsSerial: 'L7 SU - 31', notes: 'Intel i5'),
    HistoricalRecord(deskId: 'LAB7 - PC32', category: 'SYSTEM UNIT', brand: 'LENOVO', mfgSerial: 'YL00H6QJ', dntsSerial: 'L7 SU - 32', notes: 'Intel i5'),
    HistoricalRecord(deskId: 'LAB7 - PC33', category: 'SYSTEM UNIT', brand: 'LENOVO', mfgSerial: 'YL00H6QF', dntsSerial: 'L7 SU - 33', notes: 'Intel i5'),
    HistoricalRecord(deskId: 'LAB7 - PC34', category: 'SYSTEM UNIT', brand: 'LENOVO', mfgSerial: 'YL00H6QD', dntsSerial: 'L7 SU - 34', notes: 'Intel i5'),
    HistoricalRecord(deskId: 'LAB7 - PC35', category: 'SYSTEM UNIT', brand: 'LENOVO', mfgSerial: 'YL00H6R0', dntsSerial: 'L7 SU - 35', notes: 'SIR. ANDREW PATIGDAS (ENROLLMENT)'),
    HistoricalRecord(deskId: 'LAB7 - PC36', category: 'SYSTEM UNIT', brand: 'LENOVO', mfgSerial: 'YL00H6RS', dntsSerial: 'L7 SU - 36', notes: 'SIR. ANDREW PATIGDAS (ENROLLMENT)'),
    HistoricalRecord(deskId: 'LAB7 - PC37', category: 'SYSTEM UNIT', brand: 'LENOVO', mfgSerial: 'YL00H6RA', dntsSerial: 'L7 SU - 37', notes: 'SIR. ANDREW PATIGDAS (ENROLLMENT)'),
    HistoricalRecord(deskId: 'LAB7 - PC38', category: 'SYSTEM UNIT', brand: 'LENOVO', mfgSerial: 'YL00H6R5', dntsSerial: 'L7 SU - 38', notes: 'SIR. ANDREW PATIGDAS (ENROLLMENT)'),
    HistoricalRecord(deskId: 'LAB7 - PC39', category: 'SYSTEM UNIT', brand: 'LENOVO', mfgSerial: 'YL00HB5G', dntsSerial: 'L7 SU - 39', notes: 'SIR. ANDREW PATIGDAS (ENROLLMENT)'),
    HistoricalRecord(deskId: 'LAB7 - PC40', category: 'SYSTEM UNIT', brand: 'LENOVO', mfgSerial: 'YL00H6QW', dntsSerial: 'L7 SU - 40', notes: 'SIR. ANDREW PATIGDAS (ENROLLMENT)'),
    HistoricalRecord(deskId: 'LAB7 - PC41', category: 'SYSTEM UNIT', brand: 'LENOVO', mfgSerial: 'YL00HB58', dntsSerial: 'L7 SU - 41', notes: 'SIR. ANDREW PATIGDAS (ENROLLMENT)'),
    HistoricalRecord(deskId: 'LAB7 - PC42', category: 'SYSTEM UNIT', brand: 'LENOVO', mfgSerial: 'YL00H656', dntsSerial: 'L7 SU - 42', notes: 'SIR. ANDREW PATIGDAS (ENROLLMENT)'),
    HistoricalRecord(deskId: 'LAB7 - PC43', category: 'SYSTEM UNIT', brand: 'LENOVO', mfgSerial: 'YL00HB5C', dntsSerial: 'L7 SU - 43', notes: 'Intel i5'),
    HistoricalRecord(deskId: 'LAB7 - PC44', category: 'SYSTEM UNIT', brand: 'LENOVO', mfgSerial: 'YL00H6QZ_PC44', dntsSerial: 'L7 SU - 44', notes: 'Intel i5'),
    HistoricalRecord(deskId: 'LAB7 - PC45', category: 'SYSTEM UNIT', brand: 'LENOVO', mfgSerial: 'YL00H6QR', dntsSerial: 'L7 SU - 45', notes: 'Intel i5'),
    HistoricalRecord(deskId: 'LAB7 - PC46', category: 'SYSTEM UNIT', brand: 'LENOVO', mfgSerial: 'YL00H6B5W', dntsSerial: 'L7 SU - 46', notes: 'Intel i5'),
    HistoricalRecord(deskId: 'LAB7 - PC47', category: 'SYSTEM UNIT', brand: 'LENOVO', mfgSerial: 'YL00H6R8', dntsSerial: 'L6 SU - 47', notes: 'ACCOUNTING OFFICE'),
    HistoricalRecord(deskId: 'LAB7 - PC48', category: 'SYSTEM UNIT', brand: 'LENOVO', mfgSerial: 'YL00HB5L', dntsSerial: 'L7 SU - 48', notes: 'MS. KRISLY (SCHOLARSHIP)'),

    // ═══════════════════════════════════════════════════════════════════════════
    // KEYBOARDS
    // ═══════════════════════════════════════════════════════════════════════════
    HistoricalRecord(deskId: 'LAB7 - PC1', category: 'KEYBOARD', brand: 'LENOVO', mfgSerial: '95NA4EJ', dntsSerial: 'L7-K-01', notes: 'FUNCTIONAL'),
    HistoricalRecord(deskId: 'LAB7 - PC2', category: 'KEYBOARD', brand: 'LENOVO', mfgSerial: '95NA3LT', dntsSerial: 'L7-K-02', notes: 'FUNCTIONAL'),
    HistoricalRecord(deskId: 'LAB7 - PC3', category: 'KEYBOARD', brand: 'LENOVO', mfgSerial: '95NA4EG', dntsSerial: 'L7-K-03', notes: 'FUNCTIONAL'),
    HistoricalRecord(deskId: 'LAB7 - PC4', category: 'KEYBOARD', brand: 'LENOVO', mfgSerial: '95NA4DY', dntsSerial: 'L7-K-04', notes: 'FUNCTIONAL'),
    HistoricalRecord(deskId: 'LAB7 - PC5', category: 'KEYBOARD', brand: 'LENOVO', mfgSerial: '95NA4EC', dntsSerial: 'L7-K-05', notes: 'FUNCTIONAL'),
    HistoricalRecord(deskId: 'LAB7 - PC6', category: 'KEYBOARD', brand: 'LENOVO', mfgSerial: '95NA3LS', dntsSerial: 'L7-K-06', notes: 'FUNCTIONAL'),
    HistoricalRecord(deskId: 'LAB7 - PC7', category: 'KEYBOARD', brand: 'LENOVO', mfgSerial: '95NA3MD', dntsSerial: 'L7-K-07', notes: 'FUNCTIONAL'),
    HistoricalRecord(deskId: 'LAB7 - PC8', category: 'KEYBOARD', brand: 'LENOVO', mfgSerial: '95NA4DG', dntsSerial: 'L7-K-08', notes: 'FUNCTIONAL'),
    HistoricalRecord(deskId: 'LAB7 - PC9', category: 'KEYBOARD', brand: 'LENOVO', mfgSerial: '95NA4HO', dntsSerial: 'L7-K-09', notes: 'FUNCTIONAL'),
    HistoricalRecord(deskId: 'LAB7 - PC10', category: 'KEYBOARD', brand: 'LENOVO', mfgSerial: '95NA4EM', dntsSerial: 'L7-K-10', notes: 'FUNCTIONAL'),
    HistoricalRecord(deskId: 'LAB7 - PC11', category: 'KEYBOARD', brand: 'LENOVO', mfgSerial: '95NA4EH', dntsSerial: 'L7-K-11', notes: 'FUNCTIONAL'),
    HistoricalRecord(deskId: 'LAB7 - PC12', category: 'KEYBOARD', brand: 'LENOVO', mfgSerial: '95NAELY', dntsSerial: 'L7-K-12', notes: 'FUNCTIONAL'),
    HistoricalRecord(deskId: 'LAB7 - PC13', category: 'KEYBOARD', brand: 'LENOVO', mfgSerial: '95NA4GR', dntsSerial: 'L7-K-13', notes: 'FUNCTIONAL'),
    HistoricalRecord(deskId: 'LAB7 - PC14', category: 'KEYBOARD', brand: 'LENOVO', mfgSerial: '95NA4E5', dntsSerial: 'L7-K-14', notes: 'FUNCTIONAL'),
    HistoricalRecord(deskId: 'LAB7 - PC15', category: 'KEYBOARD', brand: 'LENOVO', mfgSerial: '95NA3HD', dntsSerial: 'L7-K-15', notes: 'FUNCTIONAL'),
    HistoricalRecord(deskId: 'LAB7 - PC16', category: 'KEYBOARD', brand: 'LENOVO', mfgSerial: '95NA3HC', dntsSerial: 'L7-K-16', notes: 'FUNCTIONAL'),
    HistoricalRecord(deskId: 'LAB7 - PC17', category: 'KEYBOARD', brand: 'LENOVO', mfgSerial: '95NA4DF', dntsSerial: 'L7-K-17', notes: 'FUNCTIONAL'),
    HistoricalRecord(deskId: 'LAB7 - PC18', category: 'KEYBOARD', brand: 'LENOVO', mfgSerial: '95NA3MB_PC18', dntsSerial: 'L7-K-18', notes: 'FUNCTIONAL'),
    HistoricalRecord(deskId: 'LAB7 - PC19', category: 'KEYBOARD', brand: 'LENOVO', mfgSerial: '95NA4C5', dntsSerial: 'L7-K-19', notes: 'FUNCTIONAL'),
    HistoricalRecord(deskId: 'LAB7 - PC20', category: 'KEYBOARD', brand: 'LENOVO', mfgSerial: '95NA3MB_PC20', dntsSerial: 'L7-K-20', notes: 'FUNCTIONAL'),
    HistoricalRecord(deskId: 'LAB7 - PC21', category: 'KEYBOARD', brand: 'LENOVO', mfgSerial: '95NA4EO', dntsSerial: 'L7-K-21', notes: 'FUNCTIONAL'),
    HistoricalRecord(deskId: 'LAB7 - PC22', category: 'KEYBOARD', brand: 'LENOVO', mfgSerial: '95NA4DE', dntsSerial: 'L7-K-22', notes: 'FUNCTIONAL'),
    HistoricalRecord(deskId: 'LAB7 - PC23', category: 'KEYBOARD', brand: 'LENOVO', mfgSerial: '95NA4GV', dntsSerial: 'L7-K-23', notes: 'FUNCTIONAL'),
    HistoricalRecord(deskId: 'LAB7 - PC24', category: 'KEYBOARD', brand: 'LENOVO', mfgSerial: '902AOVOJ', dntsSerial: 'L7-K-24', notes: 'FUNCTIONAL'),
    HistoricalRecord(deskId: 'LAB7 - PC25', category: 'KEYBOARD', brand: 'LENOVO', mfgSerial: '95NA4EK', dntsSerial: 'L7-K-25', notes: 'FUNCTIONAL'),
    HistoricalRecord(deskId: 'LAB7 - PC26', category: 'KEYBOARD', brand: 'LENOVO', mfgSerial: '95NA4EZ', dntsSerial: 'L7-K-26', notes: 'FUNCTIONAL'),
    HistoricalRecord(deskId: 'LAB7 - PC27', category: 'KEYBOARD', brand: 'LENOVO', mfgSerial: '95NA4BZ', dntsSerial: 'L7-K-27', notes: 'FUNCTIONAL'),
    HistoricalRecord(deskId: 'LAB7 - PC28', category: 'KEYBOARD', brand: 'LENOVO', mfgSerial: '95NA4GN', dntsSerial: 'L7-K-28', notes: 'FUNCTIONAL'),
    HistoricalRecord(deskId: 'LAB7 - PC29', category: 'KEYBOARD', brand: 'LENOVO', mfgSerial: '95NA4E1', dntsSerial: 'L7-K-29', notes: 'FUNCTIONAL'),
    HistoricalRecord(deskId: 'LAB7 - PC30', category: 'KEYBOARD', brand: 'LENOVO', mfgSerial: '95NA4EN', dntsSerial: 'L7-K-30', notes: 'FUNCTIONAL'),
    HistoricalRecord(deskId: 'LAB7 - PC31', category: 'KEYBOARD', brand: 'LENOVO', mfgSerial: '95NA4CJ', dntsSerial: 'L7-K-31', notes: 'FUNCTIONAL'),
    HistoricalRecord(deskId: 'LAB7 - PC32', category: 'KEYBOARD', brand: 'LENOVO', mfgSerial: '95NA3MC', dntsSerial: 'L7-K-32', notes: 'FUNCTIONAL'),
    HistoricalRecord(deskId: 'LAB7 - PC33', category: 'KEYBOARD', brand: 'LENOVO', mfgSerial: '95NA4CT', dntsSerial: 'L7-K-33', notes: 'FUNCTIONAL'),
    HistoricalRecord(deskId: 'LAB7 - PC34', category: 'KEYBOARD', brand: 'LENOVO', mfgSerial: '95NA3LM', dntsSerial: 'L7-K-34', notes: 'FUNCTIONAL'),
    HistoricalRecord(deskId: 'LAB7 - PC35', category: 'KEYBOARD', brand: 'LENOVO', mfgSerial: '95NA3LJ', dntsSerial: 'L7-K-35', notes: 'SIR. ANDREW PATIGDAS (ENROLLMENT)'),
    HistoricalRecord(deskId: 'LAB7 - PC36', category: 'KEYBOARD', brand: 'LENOVO', mfgSerial: '95NA4GM', dntsSerial: 'L7-K-36', notes: 'SIR. ANDREW PATIGDAS (ENROLLMENT)'),
    HistoricalRecord(deskId: 'LAB7 - PC37', category: 'KEYBOARD', brand: 'LENOVO', mfgSerial: '95NA4EE', dntsSerial: 'L7-K-37', notes: 'SIR. ANDREW PATIGDAS (ENROLLMENT)'),
    HistoricalRecord(deskId: 'LAB7 - PC38', category: 'KEYBOARD', brand: 'LENOVO', mfgSerial: '95NA3LL', dntsSerial: 'L7-K-38', notes: 'SIR. ANDREW PATIGDAS (ENROLLMENT)'),
    HistoricalRecord(deskId: 'LAB7 - PC39', category: 'KEYBOARD', brand: 'LENOVO', mfgSerial: '95NA4C8_PC39', dntsSerial: 'L7-K-39', notes: 'SIR. ANDREW PATIGDAS (ENROLLMENT)'),
    HistoricalRecord(deskId: 'LAB7 - PC40', category: 'KEYBOARD', brand: 'LENOVO', mfgSerial: '95NAA5V', dntsSerial: 'L7-K-40', notes: 'SIR. ANDREW PATIGDAS (ENROLLMENT)'),
    HistoricalRecord(deskId: 'LAB7 - PC41', category: 'KEYBOARD', brand: 'LENOVO', mfgSerial: '95NA3LN', dntsSerial: 'L7-K-41', notes: 'SIR. ANDREW PATIGDAS (ENROLLMENT)'),
    HistoricalRecord(deskId: 'LAB7 - PC42', category: 'KEYBOARD', brand: 'LENOVO', mfgSerial: '95MA07B', dntsSerial: 'L7-K-42', notes: 'SIR. ANDREW PATIGDAS (ENROLLMENT)'),
    HistoricalRecord(deskId: 'LAB7 - PC43', category: 'KEYBOARD', brand: 'LENOVO', mfgSerial: '95NA4GZ', dntsSerial: 'L7-K-43', notes: 'FUNCTIONAL'),
    HistoricalRecord(deskId: 'LAB7 - PC44', category: 'KEYBOARD', brand: 'LENOVO', mfgSerial: '95NA4C8_PC44', dntsSerial: 'L7-K-44', notes: 'FUNCTIONAL'),
    HistoricalRecord(deskId: 'LAB7 - PC45', category: 'KEYBOARD', brand: 'LENOVO', mfgSerial: '95NA3M9', dntsSerial: 'L7-K-45', notes: 'FUNCTIONAL'),
    HistoricalRecord(deskId: 'LAB7 - PC46', category: 'KEYBOARD', brand: 'LENOVO', mfgSerial: '95NA4EA', dntsSerial: 'L7-K-46', notes: 'FUNCTIONAL'),
    HistoricalRecord(deskId: 'LAB7 - PC47', category: 'KEYBOARD', brand: 'LENOVO', mfgSerial: '95NA4EB', dntsSerial: 'L6-K-47', notes: 'ACCOUNTING OFFICE'),
    HistoricalRecord(deskId: 'LAB7 - PC48', category: 'KEYBOARD', brand: 'LENOVO', mfgSerial: '95NA3MA', dntsSerial: 'L7-K-48', notes: 'MS. KRISLY (SCHOLARSHIP)'),

    // ═══════════════════════════════════════════════════════════════════════════
    // MICE
    // ═══════════════════════════════════════════════════════════════════════════
    HistoricalRecord(deskId: 'LAB7 - PC1', category: 'MOUSE', brand: 'LENOVO', mfgSerial: '96CODHF', dntsSerial: 'L7-M-01', notes: 'FUNCTIONAL'),
    HistoricalRecord(deskId: 'LAB7 - PC2', category: 'MOUSE', brand: 'LENOVO', mfgSerial: '96CODK8', dntsSerial: 'L7-M-02', notes: 'FUNCTIONAL'),
    HistoricalRecord(deskId: 'LAB7 - PC3', category: 'MOUSE', brand: 'LENOVO', mfgSerial: '96CODKV', dntsSerial: 'L7-M-03', notes: 'FUNCTIONAL'),
    HistoricalRecord(deskId: 'LAB7 - PC4', category: 'MOUSE', brand: 'LENOVO', mfgSerial: '96CODKK', dntsSerial: 'L7-M-04', notes: 'FUNCTIONAL'),
    HistoricalRecord(deskId: 'LAB7 - PC5', category: 'MOUSE', brand: 'LENOVO', mfgSerial: '96CODDB', dntsSerial: 'L7-M-05', notes: 'FUNCTIONAL'),
    HistoricalRecord(deskId: 'LAB7 - PC6', category: 'MOUSE', brand: 'LENOVO', mfgSerial: '96CODHT', dntsSerial: 'L7-M-06', notes: 'FUNCTIONAL'),
    HistoricalRecord(deskId: 'LAB7 - PC7', category: 'MOUSE', brand: 'LENOVO', mfgSerial: '96CODKL', dntsSerial: 'L7-M-07', notes: 'FUNCTIONAL'),
    HistoricalRecord(deskId: 'LAB7 - PC8', category: 'MOUSE', brand: 'LENOVO', mfgSerial: '96CODK5', dntsSerial: 'L7-M-08', notes: 'FUNCTIONAL'),
    HistoricalRecord(deskId: 'LAB7 - PC9', category: 'MOUSE', brand: 'LENOVO', mfgSerial: '96CODH8', dntsSerial: 'L7-M-09', notes: 'FUNCTIONAL'),
    HistoricalRecord(deskId: 'LAB7 - PC10', category: 'MOUSE', brand: 'LENOVO', mfgSerial: '96CODKT', dntsSerial: 'L7-M-10', notes: 'FUNCTIONAL'),
    HistoricalRecord(deskId: 'LAB7 - PC11', category: 'MOUSE', brand: 'LENOVO', mfgSerial: '96CODK2', dntsSerial: 'L7-M-11', notes: 'FUNCTIONAL'),
    HistoricalRecord(deskId: 'LAB7 - PC12', category: 'MOUSE', brand: 'LENOVO', mfgSerial: '96CODKG', dntsSerial: 'L7-M-12', notes: 'FUNCTIONAL'),
    HistoricalRecord(deskId: 'LAB7 - PC13', category: 'MOUSE', brand: 'LENOVO', mfgSerial: '96CODAZ', dntsSerial: 'L7-M-13', notes: 'FUNCTIONAL'),
    HistoricalRecord(deskId: 'LAB7 - PC14', category: 'MOUSE', brand: 'LENOVO', mfgSerial: '96CODHS', dntsSerial: 'L7-M-14', notes: 'FUNCTIONAL'),
    HistoricalRecord(deskId: 'LAB7 - PC15', category: 'MOUSE', brand: 'LENOVO', mfgSerial: '96CODKX', dntsSerial: 'L7-M-15', notes: 'FUNCTIONAL'),
    HistoricalRecord(deskId: 'LAB7 - PC16', category: 'MOUSE', brand: 'LENOVO', mfgSerial: '96CODFL', dntsSerial: 'L7-M-16', notes: 'FUNCTIONAL'),
    HistoricalRecord(deskId: 'LAB7 - PC17', category: 'MOUSE', brand: 'LENOVO', mfgSerial: '96CODJY', dntsSerial: 'L7-M-17', notes: 'FUNCTIONAL'),
    HistoricalRecord(deskId: 'LAB7 - PC18', category: 'MOUSE', brand: 'LENOVO', mfgSerial: '96CODJV', dntsSerial: 'L7-M-18', notes: 'FUNCTIONAL'),
    HistoricalRecord(deskId: 'LAB7 - PC19', category: 'MOUSE', brand: 'LENOVO', mfgSerial: 'NO_SERIAL_M19', dntsSerial: 'L7-M-19', notes: 'FUNCTIONAL'),
    HistoricalRecord(deskId: 'LAB7 - PC20', category: 'MOUSE', brand: 'LENOVO', mfgSerial: '96CODJF', dntsSerial: 'L7-M-20', notes: 'FUNCTIONAL'),
    HistoricalRecord(deskId: 'LAB7 - PC21', category: 'MOUSE', brand: 'LENOVO', mfgSerial: '96COCMA', dntsSerial: 'L7-M-21', notes: 'FUNCTIONAL'),
    HistoricalRecord(deskId: 'LAB7 - PC22', category: 'MOUSE', brand: 'LENOVO', mfgSerial: '96CODKA', dntsSerial: 'L7-M-22', notes: 'FUNCTIONAL'),
    HistoricalRecord(deskId: 'LAB7 - PC23', category: 'MOUSE', brand: 'LENOVO', mfgSerial: '96CODJM', dntsSerial: 'L7-M-23', notes: 'FUNCTIONAL'),
    HistoricalRecord(deskId: 'LAB7 - PC24', category: 'MOUSE', brand: 'LENOVO', mfgSerial: '96CODHO', dntsSerial: 'L7-M-24', notes: 'FUNCTIONAL'),
    HistoricalRecord(deskId: 'LAB7 - PC25', category: 'MOUSE', brand: 'LENOVO', mfgSerial: '96CODJX', dntsSerial: 'L7-M-25', notes: 'FUNCTIONAL'),
    HistoricalRecord(deskId: 'LAB7 - PC26', category: 'MOUSE', brand: 'LENOVO', mfgSerial: '96CODKJ', dntsSerial: 'L7-M-26', notes: 'FUNCTIONAL'),
    HistoricalRecord(deskId: 'LAB7 - PC27', category: 'MOUSE', brand: 'LENOVO', mfgSerial: '96CODHW', dntsSerial: 'L7-M-27', notes: 'FUNCTIONAL'),
    HistoricalRecord(deskId: 'LAB7 - PC28', category: 'MOUSE', brand: 'LENOVO', mfgSerial: '96CODKC', dntsSerial: 'L7-M-28', notes: 'FUNCTIONAL'),
    HistoricalRecord(deskId: 'LAB7 - PC29', category: 'MOUSE', brand: 'LENOVO', mfgSerial: '96CODJH', dntsSerial: 'L7-M-29', notes: 'FUNCTIONAL'),
    HistoricalRecord(deskId: 'LAB7 - PC30', category: 'MOUSE', brand: 'LENOVO', mfgSerial: '96CODB9', dntsSerial: 'L7-M-30', notes: 'FUNCTIONAL'),
    HistoricalRecord(deskId: 'LAB7 - PC31', category: 'MOUSE', brand: 'LENOVO', mfgSerial: '96CODK6', dntsSerial: 'L7-M-31', notes: 'FUNCTIONAL'),
    HistoricalRecord(deskId: 'LAB7 - PC32', category: 'MOUSE', brand: 'LENOVO', mfgSerial: '96CODKF', dntsSerial: 'L7-M-32', notes: 'FUNCTIONAL'),
    HistoricalRecord(deskId: 'LAB7 - PC33', category: 'MOUSE', brand: 'LENOVO', mfgSerial: '96CODJ6', dntsSerial: 'L7-M-33', notes: 'FUNCTIONAL'),
    HistoricalRecord(deskId: 'LAB7 - PC34', category: 'MOUSE', brand: 'LENOVO', mfgSerial: '96CODHX', dntsSerial: 'L7-M-34', notes: 'FUNCTIONAL'),
    HistoricalRecord(deskId: 'LAB7 - PC35', category: 'MOUSE', brand: 'LENOVO', mfgSerial: '97206HO', dntsSerial: 'L7-M-35', notes: 'SIR. ANDREW PATIGDAS (ENROLLMENT)'),
    HistoricalRecord(deskId: 'LAB7 - PC36', category: 'MOUSE', brand: 'LENOVO', mfgSerial: '96CODJD', dntsSerial: 'L7-M-36', notes: 'SIR. ANDREW PATIGDAS (ENROLLMENT)'),
    HistoricalRecord(deskId: 'LAB7 - PC37', category: 'MOUSE', brand: 'LENOVO', mfgSerial: '96CODJP', dntsSerial: 'L7-M-37', notes: 'SIR. ANDREW PATIGDAS (ENROLLMENT)'),
    HistoricalRecord(deskId: 'LAB7 - PC38', category: 'MOUSE', brand: 'LENOVO', mfgSerial: '96CODK1', dntsSerial: 'L7-M-38', notes: 'SIR. ANDREW PATIGDAS (ENROLLMENT)'),
    HistoricalRecord(deskId: 'LAB7 - PC39', category: 'MOUSE', brand: 'LENOVO', mfgSerial: '96H22FN', dntsSerial: 'L7-M-39', notes: 'SIR. ANDREW PATIGDAS (ENROLLMENT)'),
    HistoricalRecord(deskId: 'LAB7 - PC40', category: 'MOUSE', brand: 'LENOVO', mfgSerial: '96CODKR', dntsSerial: 'L7-M-40', notes: 'SIR. ANDREW PATIGDAS (ENROLLMENT)'),
    HistoricalRecord(deskId: 'LAB7 - PC41', category: 'MOUSE', brand: 'LENOVO', mfgSerial: '96CODJG', dntsSerial: 'L7-M-41', notes: 'SIR. ANDREW PATIGDAS (ENROLLMENT)'),
    HistoricalRecord(deskId: 'LAB7 - PC42', category: 'MOUSE', brand: 'LENOVO', mfgSerial: '96CODJN', dntsSerial: 'L7-M-42', notes: 'SIR. ANDREW PATIGDAS (ENROLLMENT)'),
    HistoricalRecord(deskId: 'LAB7 - PC43', category: 'MOUSE', brand: 'LENOVO', mfgSerial: '97205H9', dntsSerial: 'L7-M-43', notes: 'FUNCTIONAL'),
    HistoricalRecord(deskId: 'LAB7 - PC44', category: 'MOUSE', brand: 'LENOVO', mfgSerial: '96C0DJZ', dntsSerial: 'L7-M-44', notes: 'FUNCTIONAL'),
    HistoricalRecord(deskId: 'LAB7 - PC45', category: 'MOUSE', brand: 'A4TECH', mfgSerial: '23XWU01_PC45', dntsSerial: 'L7-M-45', notes: 'FUNCTIONAL'),
    HistoricalRecord(deskId: 'LAB7 - PC46', category: 'MOUSE', brand: 'LENOVO', mfgSerial: '97205HA', dntsSerial: 'L7-M-46', notes: 'FUNCTIONAL'),
    HistoricalRecord(deskId: 'LAB7 - PC47', category: 'MOUSE', brand: 'A4TECH', mfgSerial: '23XWU01_L6', dntsSerial: 'L6-M-47', notes: 'ACCOUNTING OFFICE'),
    HistoricalRecord(deskId: 'LAB7 - PC48', category: 'MOUSE', brand: 'LENOVO', mfgSerial: '96C0DK7', dntsSerial: 'L7-M-48', notes: 'MS. KRISLY (SCHOLARSHIP)'),

    // ═══════════════════════════════════════════════════════════════════════════
    // AVRs
    // ═══════════════════════════════════════════════════════════════════════════
    HistoricalRecord(deskId: 'LAB7 - PC1', category: 'AVR', brand: 'POWER', mfgSerial: 'L7-AVR-01', dntsSerial: 'L7-AVR-01', notes: 'FUNCTIONAL'),
    HistoricalRecord(deskId: 'LAB7 - PC2', category: 'AVR', brand: 'POWER', mfgSerial: '747414', dntsSerial: 'L7-AVR-02', notes: 'FUNCTIONAL'),
    HistoricalRecord(deskId: 'LAB7 - PC3', category: 'AVR', brand: 'SECURE', mfgSerial: 'L7-AVR-03', dntsSerial: 'L7-AVR-03', notes: 'FUNCTIONAL'),
    HistoricalRecord(deskId: 'LAB7 - PC4', category: 'AVR', brand: 'POWER', mfgSerial: 'L7-AVR-04', dntsSerial: 'L7-AVR-04', notes: 'FUNCTIONAL'),
    HistoricalRecord(deskId: 'LAB7 - PC5', category: 'AVR', brand: 'GIANT', mfgSerial: 'L7-AVR-05', dntsSerial: 'L7-AVR-05', notes: 'FUNCTIONAL'),
    HistoricalRecord(deskId: 'LAB7 - PC6', category: 'AVR', brand: 'GIANT', mfgSerial: 'L7-AVR-06', dntsSerial: 'L7-AVR-06', notes: 'FUNCTIONAL'),
    HistoricalRecord(deskId: 'LAB7 - PC7', category: 'AVR', brand: 'GIANT', mfgSerial: 'L7-AVR-07', dntsSerial: 'L7-AVR-07', notes: 'FUNCTIONAL'),
    HistoricalRecord(deskId: 'LAB7 - PC8', category: 'AVR', brand: 'MONSTER', mfgSerial: 'L7-AVR-08', dntsSerial: 'L7-AVR-08', notes: 'FUNCTIONAL'),
    HistoricalRecord(deskId: 'LAB7 - PC9', category: 'AVR', brand: 'GIANT', mfgSerial: 'L7-AVR-09', dntsSerial: 'L7-AVR-09', notes: 'FUNCTIONAL'),
    HistoricalRecord(deskId: 'LAB7 - PC10', category: 'AVR', brand: 'MONSTER', mfgSerial: 'L7-AVR-10', dntsSerial: 'L7-AVR-10', notes: 'FUNCTIONAL'),
    HistoricalRecord(deskId: 'LAB7 - PC11', category: 'AVR', brand: 'POWER', mfgSerial: 'L7-AVR-11', dntsSerial: 'L7-AVR-11', notes: 'FUNCTIONAL'),
    HistoricalRecord(deskId: 'LAB7 - PC12', category: 'AVR', brand: 'GIANT', mfgSerial: 'L7-AVR-12', dntsSerial: 'L7-AVR-12', notes: 'FUNCTIONAL'),
    HistoricalRecord(deskId: 'LAB7 - PC13', category: 'AVR', brand: 'GIANT', mfgSerial: 'L7-AVR-13', dntsSerial: 'L7-AVR-13', notes: 'FUNCTIONAL'),
    HistoricalRecord(deskId: 'LAB7 - PC14', category: 'AVR', brand: 'VIP', mfgSerial: 'L7-AVR-14', dntsSerial: 'L7-AVR-14', notes: 'FUNCTIONAL'),
    HistoricalRecord(deskId: 'LAB7 - PC15', category: 'AVR', brand: 'SECURE', mfgSerial: 'L7-AVR-15', dntsSerial: 'L7-AVR-15', notes: 'FUNCTIONAL'),
    HistoricalRecord(deskId: 'LAB7 - PC16', category: 'AVR', brand: 'GIANT', mfgSerial: 'L7-AVR-16', dntsSerial: 'L7-AVR-16', notes: 'FUNCTIONAL'),
    HistoricalRecord(deskId: 'LAB7 - PC17', category: 'AVR', brand: 'POWER', mfgSerial: 'L7-AVR-17', dntsSerial: 'L7-AVR-17', notes: 'FUNCTIONAL'),
    HistoricalRecord(deskId: 'LAB7 - PC18', category: 'AVR', brand: 'GIANT', mfgSerial: 'L7-AVR-18', dntsSerial: 'L7-AVR-18', notes: 'FUNCTIONAL'),
    HistoricalRecord(deskId: 'LAB7 - PC19', category: 'AVR', brand: 'VIP', mfgSerial: 'L7-AVR-19', dntsSerial: 'L7-AVR-19', notes: 'FUNCTIONAL'),
    HistoricalRecord(deskId: 'LAB7 - PC20', category: 'AVR', brand: 'MONSTER', mfgSerial: 'L7-AVR-20', dntsSerial: 'L7-AVR-20', notes: 'FUNCTIONAL'),
    HistoricalRecord(deskId: 'LAB7 - PC21', category: 'AVR', brand: 'GIANT', mfgSerial: 'L7-AVR-21', dntsSerial: 'L7-AVR-21', notes: 'FUNCTIONAL'),
    HistoricalRecord(deskId: 'LAB7 - PC22', category: 'AVR', brand: 'POWERBOXX', mfgSerial: 'L7-AVR-22', dntsSerial: 'L7-AVR-22', notes: 'FUNCTIONAL'),
    HistoricalRecord(deskId: 'LAB7 - PC23', category: 'AVR', brand: 'MONSTER', mfgSerial: 'L7-AVR-23', dntsSerial: 'L7-AVR-23', notes: 'FUNCTIONAL'),
    HistoricalRecord(deskId: 'LAB7 - PC24', category: 'AVR', brand: 'POWER', mfgSerial: '681594', dntsSerial: 'L7-AVR-24', notes: 'FUNCTIONAL'),
    HistoricalRecord(deskId: 'LAB7 - PC25', category: 'AVR', brand: 'GIANT', mfgSerial: 'L7-AVR-25', dntsSerial: 'L7-AVR-25', notes: 'FUNCTIONAL'),
    HistoricalRecord(deskId: 'LAB7 - PC26', category: 'AVR', brand: 'RADIUS', mfgSerial: '986998', dntsSerial: 'L7-AVR-26', notes: 'FUNCTIONAL'),
    HistoricalRecord(deskId: 'LAB7 - PC27', category: 'AVR', brand: 'GIANT', mfgSerial: 'L7-AVR-27', dntsSerial: 'L7-AVR-27', notes: 'FUNCTIONAL'),
    HistoricalRecord(deskId: 'LAB7 - PC28', category: 'AVR', brand: 'POWER', mfgSerial: '716100', dntsSerial: 'L7-AVR-28', notes: 'FUNCTIONAL'),
    HistoricalRecord(deskId: 'LAB7 - PC29', category: 'AVR', brand: 'MONSTER', mfgSerial: 'L7-AVR-29', dntsSerial: 'L7-AVR-29', notes: 'FUNCTIONAL'),
    HistoricalRecord(deskId: 'LAB7 - PC30', category: 'AVR', brand: 'POWER', mfgSerial: '651605', dntsSerial: 'L7-AVR-30', notes: 'FUNCTIONAL'),
    HistoricalRecord(deskId: 'LAB7 - PC31', category: 'AVR', brand: 'GIANT', mfgSerial: 'L7-AVR-31', dntsSerial: 'L7-AVR-31', notes: 'FUNCTIONAL'),
    HistoricalRecord(deskId: 'LAB7 - PC32', category: 'AVR', brand: 'VIP', mfgSerial: 'L7-AVR-32', dntsSerial: 'L7-AVR-32', notes: 'FUNCTIONAL'),
    HistoricalRecord(deskId: 'LAB7 - PC33', category: 'AVR', brand: 'POWERBOXX', mfgSerial: 'L7-AVR-33', dntsSerial: 'L7-AVR-33', notes: 'FUNCTIONAL'),
    HistoricalRecord(deskId: 'LAB7 - PC34', category: 'AVR', brand: 'SECURE', mfgSerial: 'L7-AVR-34', dntsSerial: 'L7-AVR-34', notes: 'FUNCTIONAL'),
    HistoricalRecord(deskId: 'LAB7 - PC35', category: 'AVR', brand: 'GIANT', mfgSerial: 'L7-AVR-35', dntsSerial: 'L7-AVR-35', notes: 'SIR. ANDREW PATIGDAS (ENROLLMENT)'),
    HistoricalRecord(deskId: 'LAB7 - PC36', category: 'AVR', brand: 'MONSTER', mfgSerial: 'L7-AVR-36', dntsSerial: 'L7-AVR-36', notes: 'SIR. ANDREW PATIGDAS (ENROLLMENT)'),
    HistoricalRecord(deskId: 'LAB7 - PC37', category: 'AVR', brand: 'GIANT', mfgSerial: 'L7-AVR-37', dntsSerial: 'L7-AVR-37', notes: 'SIR. ANDREW PATIGDAS (ENROLLMENT)'),
    HistoricalRecord(deskId: 'LAB7 - PC38', category: 'AVR', brand: 'GIANT', mfgSerial: 'L7-AVR-38', dntsSerial: 'L7-AVR-38', notes: 'SIR. ANDREW PATIGDAS (ENROLLMENT)'),
    HistoricalRecord(deskId: 'LAB7 - PC39', category: 'AVR', brand: 'MONSTER', mfgSerial: 'L7-AVR-39', dntsSerial: 'L7-AVR-39', notes: 'SIR. ANDREW PATIGDAS (ENROLLMENT)'),
    HistoricalRecord(deskId: 'LAB7 - PC40', category: 'AVR', brand: 'MONSTER', mfgSerial: 'L7-AVR-40', dntsSerial: 'L7-AVR-40', notes: 'SIR. ANDREW PATIGDAS (ENROLLMENT)'),
    HistoricalRecord(deskId: 'LAB7 - PC41', category: 'AVR', brand: 'GIANT', mfgSerial: 'L7-AVR-41', dntsSerial: 'L7-AVR-41', notes: 'SIR. ANDREW PATIGDAS (ENROLLMENT)'),
    HistoricalRecord(deskId: 'LAB7 - PC42', category: 'AVR', brand: 'MONSTER', mfgSerial: 'L7-AVR-42', dntsSerial: 'L7-AVR-42', notes: 'SIR. ANDREW PATIGDAS (ENROLLMENT)'),
    HistoricalRecord(deskId: 'LAB7 - PC43', category: 'AVR', brand: 'MONSTER', mfgSerial: 'L7-AVR-43', dntsSerial: 'L7-AVR-43', notes: 'FUNCTIONAL'),
    HistoricalRecord(deskId: 'LAB7 - PC44', category: 'AVR', brand: 'GIANT', mfgSerial: 'L7-AVR-44', dntsSerial: 'L7-AVR-44', notes: 'FUNCTIONAL'),
    HistoricalRecord(deskId: 'LAB7 - PC45', category: 'AVR', brand: 'MONSTER', mfgSerial: 'L7-AVR-45', dntsSerial: 'L7-AVR-45', notes: 'FUNCTIONAL'),
    HistoricalRecord(deskId: 'LAB7 - PC46', category: 'AVR', brand: 'POWER', mfgSerial: 'L7-AVR-46', dntsSerial: 'L7-AVR-46', notes: 'FUNCTIONAL'),
    HistoricalRecord(deskId: 'LAB7 - PC47', category: 'AVR', brand: 'POWER', mfgSerial: 'L6-AVR-47', dntsSerial: 'L6-AVR-47', notes: 'ACCOUNTING OFFICE'),
    HistoricalRecord(deskId: 'LAB7 - PC48', category: 'AVR', brand: 'SECURE', mfgSerial: 'L7-AVR-48', dntsSerial: 'L7-AVR-48', notes: 'MS. KRISLY (SCHOLARSHIP)'),

    // ═══════════════════════════════════════════════════════════════════════════
    // SSDs (NVME)
    // ═══════════════════════════════════════════════════════════════════════════
    HistoricalRecord(deskId: 'LAB7 - PC1', category: 'SSD', brand: 'SAMSUNG', mfgSerial: '0025_3886_91BD_8D51', dntsSerial: 'L7 SSD - 01', notes: 'FUNCTIONAL'),
    HistoricalRecord(deskId: 'LAB7 - PC2', category: 'SSD', brand: 'SAMSUNG', mfgSerial: '0025_3886_91BD_8D9C', dntsSerial: 'L7 SSD - 02', notes: 'FUNCTIONAL'),
    HistoricalRecord(deskId: 'LAB7 - PC3', category: 'SSD', brand: 'SAMSUNG', mfgSerial: '0025_3886_91BD_8D68', dntsSerial: 'L7 SSD - 03', notes: 'FUNCTIONAL'),
    HistoricalRecord(deskId: 'LAB7 - PC4', category: 'SSD', brand: 'SAMSUNG', mfgSerial: '0025_3886_91BD_8D59', dntsSerial: 'L7 SSD - 04', notes: 'FUNCTIONAL'),
    HistoricalRecord(deskId: 'LAB7 - PC5', category: 'SSD', brand: 'SAMSUNG', mfgSerial: '0025_3886_91BD_8D23', dntsSerial: 'L7 SSD - 05', notes: 'FUNCTIONAL'),
    HistoricalRecord(deskId: 'LAB7 - PC6', category: 'SSD', brand: 'SAMSUNG', mfgSerial: '0025_3886_91BD_8D22', dntsSerial: 'L7 SSD - 06', notes: 'FUNCTIONAL'),
    HistoricalRecord(deskId: 'LAB7 - PC7', category: 'SSD', brand: 'SAMSUNG', mfgSerial: '0025_3886_91BD_8DA9', dntsSerial: 'L7 SSD - 07', notes: 'FUNCTIONAL'),
    HistoricalRecord(deskId: 'LAB7 - PC8', category: 'SSD', brand: 'SAMSUNG', mfgSerial: '0025_3886_91BD_8BAB', dntsSerial: 'L7 SSD - 08', notes: 'FUNCTIONAL'),
    HistoricalRecord(deskId: 'LAB7 - PC9', category: 'SSD', brand: 'SAMSUNG', mfgSerial: '0025_3886_91BD_8D2A', dntsSerial: 'L7 SSD - 09', notes: 'FUNCTIONAL'),
    HistoricalRecord(deskId: 'LAB7 - PC10', category: 'SSD', brand: 'SAMSUNG', mfgSerial: '0025_3886_91BD_8BE6', dntsSerial: 'L7 SSD - 10', notes: 'FUNCTIONAL'),
    HistoricalRecord(deskId: 'LAB7 - PC11', category: 'SSD', brand: 'SAMSUNG', mfgSerial: '0025_3886_91BD_8BF3', dntsSerial: 'L7 SSD - 11', notes: 'FUNCTIONAL'),
    HistoricalRecord(deskId: 'LAB7 - PC12', category: 'SSD', brand: 'SAMSUNG', mfgSerial: '0025_3886_91BD_8D5A', dntsSerial: 'L7 SSD - 12', notes: 'FUNCTIONAL'),
    HistoricalRecord(deskId: 'LAB7 - PC13', category: 'SSD', brand: 'SAMSUNG', mfgSerial: '0025_3886_91BD_8D1B', dntsSerial: 'L7 SSD - 13', notes: 'FUNCTIONAL'),
    HistoricalRecord(deskId: 'LAB7 - PC14', category: 'SSD', brand: 'SAMSUNG', mfgSerial: '0025_3886_91BD_8D27', dntsSerial: 'L7 SSD - 14', notes: 'FUNCTIONAL'),
    HistoricalRecord(deskId: 'LAB7 - PC15', category: 'SSD', brand: 'SAMSUNG', mfgSerial: '0025_3886_91BD_8BC8', dntsSerial: 'L7 SSD - 15', notes: 'FUNCTIONAL'),
    HistoricalRecord(deskId: 'LAB7 - PC16', category: 'SSD', brand: 'SAMSUNG', mfgSerial: '0025_3886_91BD_8D42', dntsSerial: 'L7 SSD - 16', notes: 'FUNCTIONAL'),
    HistoricalRecord(deskId: 'LAB7 - PC17', category: 'SSD', brand: 'SAMSUNG', mfgSerial: '0025_3886_91BD_8D69', dntsSerial: 'L7 SSD - 17', notes: 'FUNCTIONAL'),
    HistoricalRecord(deskId: 'LAB7 - PC18', category: 'SSD', brand: 'SAMSUNG', mfgSerial: '0025_3886_91BD_8D24', dntsSerial: 'L7 SSD - 18', notes: 'FUNCTIONAL'),
    HistoricalRecord(deskId: 'LAB7 - PC19', category: 'SSD', brand: 'SAMSUNG', mfgSerial: '0025_3886_91BD_8BEF', dntsSerial: 'L7 SSD - 19', notes: 'FUNCTIONAL'),
    HistoricalRecord(deskId: 'LAB7 - PC20', category: 'SSD', brand: 'SAMSUNG', mfgSerial: '0025_3886_91BD_8BE3', dntsSerial: 'L7 SSD - 20', notes: 'FUNCTIONAL'),
    HistoricalRecord(deskId: 'LAB7 - PC21', category: 'SSD', brand: 'SAMSUNG', mfgSerial: '0025_3886_91BD_8D2B', dntsSerial: 'L7 SSD - 21', notes: 'FUNCTIONAL'),
    HistoricalRecord(deskId: 'LAB7 - PC22', category: 'SSD', brand: 'SAMSUNG', mfgSerial: '0025_3886_91BD_8D34', dntsSerial: 'L7 SSD - 22', notes: 'FUNCTIONAL'),
    HistoricalRecord(deskId: 'LAB7 - PC23', category: 'SSD', brand: 'SAMSUNG', mfgSerial: '0025_3886_91BD_8D52', dntsSerial: 'L7 SSD - 23', notes: 'FUNCTIONAL'),
    HistoricalRecord(deskId: 'LAB7 - PC24', category: 'SSD', brand: 'SAMSUNG', mfgSerial: '0025_3886_91BD_8BA1', dntsSerial: 'L7 SSD - 24', notes: 'FUNCTIONAL'),
    HistoricalRecord(deskId: 'LAB7 - PC25', category: 'SSD', brand: 'SAMSUNG', mfgSerial: '0025_3886_91BD_8D45', dntsSerial: 'L7 SSD - 25', notes: 'FUNCTIONAL'),
    HistoricalRecord(deskId: 'LAB7 - PC26', category: 'SSD', brand: 'SAMSUNG', mfgSerial: '0025_3886_91BD_8D32', dntsSerial: 'L7 SSD - 26', notes: 'FUNCTIONAL'),
    HistoricalRecord(deskId: 'LAB7 - PC27', category: 'SSD', brand: 'SAMSUNG', mfgSerial: '0025_3886_91BD_8BA3', dntsSerial: 'L7 SSD - 27', notes: 'FUNCTIONAL'),
    HistoricalRecord(deskId: 'LAB7 - PC28', category: 'SSD', brand: 'SAMSUNG', mfgSerial: '0025_3886_91BD_8BAF', dntsSerial: 'L7 SSD - 28', notes: 'FUNCTIONAL'),
    HistoricalRecord(deskId: 'LAB7 - PC29', category: 'SSD', brand: 'SAMSUNG', mfgSerial: '0025_3886_91BD_8BBE', dntsSerial: 'L7 SSD - 29', notes: 'FUNCTIONAL'),
    HistoricalRecord(deskId: 'LAB7 - PC30', category: 'SSD', brand: 'SAMSUNG', mfgSerial: '0025_3886_91BD_8DC2', dntsSerial: 'L7 SSD - 30', notes: 'FUNCTIONAL'),
    HistoricalRecord(deskId: 'LAB7 - PC31', category: 'SSD', brand: 'SAMSUNG', mfgSerial: '0025_3886_91BD_8D1E', dntsSerial: 'L7 SSD - 31', notes: 'FUNCTIONAL'),
    HistoricalRecord(deskId: 'LAB7 - PC32', category: 'SSD', brand: 'SAMSUNG', mfgSerial: '0025_3886_91BD_8D9D', dntsSerial: 'L7 SSD - 32', notes: 'FUNCTIONAL'),
    HistoricalRecord(deskId: 'LAB7 - PC33', category: 'SSD', brand: 'SAMSUNG', mfgSerial: '0025_3886_91BD_8D9B', dntsSerial: 'L7 SSD - 33', notes: 'FUNCTIONAL'),
    HistoricalRecord(deskId: 'LAB7 - PC34', category: 'SSD', brand: 'SAMSUNG', mfgSerial: '0025_3886_91BD_3DC3', dntsSerial: 'L7 SSD - 34', notes: 'FUNCTIONAL'),
    HistoricalRecord(deskId: 'LAB7 - PC35', category: 'SSD', brand: 'SAMSUNG', mfgSerial: '0025_3886_91BD_8BAE', dntsSerial: 'L7 SSD - 35', notes: 'SIR. ANDREW PATIGDAS (ENROLLMENT)'),
    HistoricalRecord(deskId: 'LAB7 - PC36', category: 'SSD', brand: 'SAMSUNG', mfgSerial: '0025_3886_91BD_8D44', dntsSerial: 'L7 SSD - 36', notes: 'SIR. ANDREW PATIGDAS (ENROLLMENT)'),
    HistoricalRecord(deskId: 'LAB7 - PC37', category: 'SSD', brand: 'SAMSUNG', mfgSerial: '0025_3886_91BD_8D5C', dntsSerial: 'L7 SSD - 37', notes: 'SIR. ANDREW PATIGDAS (ENROLLMENT)'),
    HistoricalRecord(deskId: 'LAB7 - PC38', category: 'SSD', brand: 'SAMSUNG', mfgSerial: '0025_3886_91BD_8DA4', dntsSerial: 'L7 SSD - 38', notes: 'SIR. ANDREW PATIGDAS (ENROLLMENT)'),
    HistoricalRecord(deskId: 'LAB7 - PC39', category: 'SSD', brand: 'SAMSUNG', mfgSerial: '0025_3886_91BD_939A', dntsSerial: 'L7 SSD - 39', notes: 'SIR. ANDREW PATIGDAS (ENROLLMENT)'),
    HistoricalRecord(deskId: 'LAB7 - PC40', category: 'SSD', brand: 'SAMSUNG', mfgSerial: '0025_3886_91BD_8BBB', dntsSerial: 'L7 SSD - 40', notes: 'SIR. ANDREW PATIGDAS (ENROLLMENT)'),
    HistoricalRecord(deskId: 'LAB7 - PC41', category: 'SSD', brand: 'SAMSUNG', mfgSerial: '0025_3886_91BD_93B6', dntsSerial: 'L7 SSD - 41', notes: 'SIR. ANDREW PATIGDAS (ENROLLMENT)'),
    HistoricalRecord(deskId: 'LAB7 - PC42', category: 'SSD', brand: 'SAMSUNG', mfgSerial: '0025_3886_91BD_8D1D', dntsSerial: 'L7 SSD - 42', notes: 'FUNCTIONAL'),
    HistoricalRecord(deskId: 'LAB7 - PC43', category: 'SSD', brand: 'SAMSUNG', mfgSerial: '0025_3886_91BD_93C2', dntsSerial: 'L7 SSD - 43', notes: 'FUNCTIONAL'),
    HistoricalRecord(deskId: 'LAB7 - PC44', category: 'SSD', brand: 'SAMSUNG', mfgSerial: '0025_3886_91BD_8BD3', dntsSerial: 'L7 SSD - 44', notes: 'FUNCTIONAL'),
    HistoricalRecord(deskId: 'LAB7 - PC45', category: 'SSD', brand: 'SAMSUNG', mfgSerial: '0025_3886_91BD_8BBA', dntsSerial: 'L7 SSD - 45', notes: 'FUNCTIONAL'),
    HistoricalRecord(deskId: 'LAB7 - PC46', category: 'SSD', brand: 'SAMSUNG', mfgSerial: '0025_3886_91BD_9396', dntsSerial: 'L7 SSD - 46', notes: 'FUNCTIONAL'),
    HistoricalRecord(deskId: 'LAB7 - PC47', category: 'SSD', brand: 'SAMSUNG', mfgSerial: '0025_3886_91BD_8D93', dntsSerial: 'L6 SSD - 47', notes: 'ACCOUNTING OFFICE'),
    HistoricalRecord(deskId: 'LAB7 - PC48', category: 'SSD', brand: 'SAMSUNG', mfgSerial: '0025_3886_91BD_939B', dntsSerial: 'L7 SSD - 48', notes: 'MS. KRISLY (SCHOLARSHIP)'),
  ];
}
