import 'historical_baseline_provider.dart';

class HistoricalMonitorsLab6 {
  static const List<HistoricalRecord> monitorData = [
    HistoricalRecord(
      deskId: 'LAB6 - PC1',
      category: 'MONITOR',
      brand: 'ACER',
      mfgSerial: '253Q02129',
      dntsSerial: 'L6-MR-02',
      dateAcquired: 'August 2, 2025',
      notes: 'FUNCTIONAL',
    ),
    HistoricalRecord(
      deskId: 'LAB6 - PC2',
      category: 'MONITOR',
      brand: 'ACER',
      mfgSerial: '252401944',
      dntsSerial: 'L6-MR-03',
      dateAcquired: 'August 2, 2025',
      notes: 'FUNCTIONAL',
    ),
    HistoricalRecord(
      deskId: 'LAB6 - PC3',
      category: 'MONITOR',
      brand: 'ACER',
      mfgSerial: '253R17573',
      dntsSerial: 'L6-MR-03',
      dateAcquired: 'August 2, 2025',
      notes: 'FUNCTIONAL',
    ),
    HistoricalRecord(
      deskId: 'LAB6 - PC4',
      category: 'MONITOR',
      brand: 'ACER',
      mfgSerial: '253R16416',
      dntsSerial: 'L6-MR-04',
      dateAcquired: 'August 2, 2025',
      notes: 'FUNCTIONAL',
    ),
    HistoricalRecord(
      deskId: 'LAB6 - PC5',
      category: 'MONITOR',
      brand: 'ACER',
      mfgSerial: '253R17617',
      dntsSerial: 'L6-MR-05',
      dateAcquired: 'August 2, 2025',
      notes: 'FUNCTIONAL',
    ),
    HistoricalRecord(
      deskId: 'LAB6 - PC6',
      category: 'MONITOR',
      brand: 'ACER',
      mfgSerial: '252401320',
      dntsSerial: 'L6-MR-06',
      dateAcquired: 'August 2, 2025',
      notes: 'FUNCTIONAL',
    ),
    HistoricalRecord(
      deskId: 'LAB6 - PC7',
      category: 'MONITOR',
      brand: 'ACER',
      mfgSerial: '253Q01827',
      dntsSerial: 'L6-MR-07',
      dateAcquired: 'August 2, 2025',
      notes: 'FUNCTIONAL',
    ),
    HistoricalRecord(
      deskId: 'LAB6 - PC8',
      category: 'MONITOR',
      brand: 'ACER',
      mfgSerial: '253R174563',
      dntsSerial: 'L6-MR-08',
      dateAcquired: 'August 2, 2025',
      notes: 'FUNCTIONAL',
    ),
    HistoricalRecord(
      deskId: 'LAB6 - PC9',
      category: 'MONITOR',
      brand: 'ACER',
      mfgSerial: '253R17430',
      dntsSerial: 'L6-MR-09',
      dateAcquired: 'August 2, 2025',
      notes: 'FUNCTIONAL',
    ),
    HistoricalRecord(
      deskId: 'LAB6 - PC10',
      category: 'MONITOR',
      brand: 'ACER',
      mfgSerial: '253R17429',
      dntsSerial: 'L6-MR-10',
      dateAcquired: 'August 2, 2025',
      notes: 'FUNCTIONAL',
    ),
    HistoricalRecord(
      deskId: 'LAB6 - PC11',
      category: 'MONITOR',
      brand: 'ACER',
      mfgSerial: '252401293',
      dntsSerial: 'L6-MR-11',
      dateAcquired: 'August 2, 2025',
      notes: 'FUNCTIONAL',
    ),
    HistoricalRecord(
      deskId: 'LAB6 - PC12',
      category: 'MONITOR',
      brand: 'ACER',
      mfgSerial: '253Q01823',
      dntsSerial: 'L6-MR-12',
      dateAcquired: 'August 2, 2025',
      notes: 'FUNCTIONAL',
    ),
    HistoricalRecord(
      deskId: 'LAB6 - PC13',
      category: 'MONITOR',
      brand: 'ACER',
      mfgSerial: '253R17121',
      dntsSerial: 'L6-MR-13',
      dateAcquired: 'August 2, 2025',
      notes: 'FUNCTIONAL',
    ),
    HistoricalRecord(
      deskId: 'LAB6 - PC14',
      category: 'MONITOR',
      brand: 'ACER',
      mfgSerial: '252401091',
      dntsSerial: 'L6-MR-14',
      dateAcquired: 'August 2, 2025',
      notes: 'FUNCTIONAL',
    ),
    HistoricalRecord(
      deskId: 'LAB6 - PC15',
      category: 'MONITOR',
      brand: 'ACER',
      mfgSerial: '253R17642',
      dntsSerial: 'L6-MR-15',
      dateAcquired: 'August 2, 2025',
      notes: 'FUNCTIONAL',
    ),
    HistoricalRecord(
      deskId: 'LAB6 - PC16',
      category: 'MONITOR',
      brand: 'ACER',
      mfgSerial: '253Q01826',
      dntsSerial: 'L6-MR-16',
      dateAcquired: 'August 2, 2025',
      notes: 'FUNCTIONAL',
    ),
    HistoricalRecord(
      deskId: 'LAB6 - PC17',
      category: 'MONITOR',
      brand: 'ACER',
      mfgSerial: '252401962',
      dntsSerial: 'L6-MR-17',
      dateAcquired: 'August 2, 2025',
      notes: 'FUNCTIONAL',
    ),
    HistoricalRecord(
      deskId: 'LAB6 - PC18',
      category: 'MONITOR',
      brand: 'ACER',
      mfgSerial: '253R17624',
      dntsSerial: 'L6-MR-18',
      dateAcquired: 'August 2, 2025',
      notes: 'FUNCTIONAL',
    ),
    HistoricalRecord(
      deskId: 'LAB6 - PC19',
      category: 'MONITOR',
      brand: 'ACER',
      mfgSerial: '253R17555',
      dntsSerial: 'L6-MR-19',
      dateAcquired: 'August 2, 2025',
      notes: 'FUNCTIONAL',
    ),
    HistoricalRecord(
      deskId: 'LAB6 - PC20',
      category: 'MONITOR',
      brand: 'ACER',
      mfgSerial: '253R17595',
      dntsSerial: 'L6-MR-20',
      dateAcquired: 'August 2, 2025',
      notes: 'FUNCTIONAL',
    ),
    HistoricalRecord(
      deskId: 'LAB6 - PC21',
      category: 'MONITOR',
      brand: 'ACER',
      mfgSerial: '252401083',
      dntsSerial: 'L6-MR-21',
      dateAcquired: 'August 2, 2025',
      notes: 'FUNCTIONAL',
    ),
    HistoricalRecord(
      deskId: 'LAB6 - PC22',
      category: 'MONITOR',
      brand: 'ACER',
      mfgSerial: '253R17541',
      dntsSerial: 'L6-MR-22',
      dateAcquired: 'August 2, 2025',
      notes: 'FUNCTIONAL',
    ),
    HistoricalRecord(
      deskId: 'LAB6 - PC23',
      category: 'MONITOR',
      brand: 'ACER',
      mfgSerial: '253Q01863',
      dntsSerial: 'L6-MR-23',
      dateAcquired: 'August 2, 2025',
      notes: 'FUNCTIONAL',
    ),
    HistoricalRecord(
      deskId: 'LAB6 - PC24',
      category: 'MONITOR',
      brand: 'ACER',
      mfgSerial: '253R17110',
      dntsSerial: 'L6-MR-24',
      dateAcquired: 'August 2, 2025',
      notes: 'FUNCTIONAL',
    ),
    HistoricalRecord(
      deskId: 'LAB6 - PC25',
      category: 'MONITOR',
      brand: 'ACER',
      mfgSerial: '253R17510',
      dntsSerial: 'L6-MR-24',
      dateAcquired: 'August 2, 2025',
      notes: 'FUNCTIONAL',
    ),
    HistoricalRecord(
      deskId: 'LAB6 - PC26',
      category: 'MONITOR',
      brand: 'ACER',
      mfgSerial: '253R17645',
      dntsSerial: 'L6-MR-26',
      dateAcquired: 'August 2, 2025',
      notes: 'FUNCTIONAL',
    ),
    HistoricalRecord(
      deskId: 'LAB6 - PC27',
      category: 'MONITOR',
      brand: 'ACER',
      mfgSerial: '253Q02158',
      dntsSerial: 'L6-MR-27',
      dateAcquired: 'August 2, 2025',
      notes: 'FUNCTIONAL',
    ),
    HistoricalRecord(
      deskId: 'LAB6 - PC28',
      category: 'MONITOR',
      brand: 'ACER',
      mfgSerial: '253R17124',
      dntsSerial: 'L6-MR-28',
      dateAcquired: 'August 2, 2025',
      notes: 'FUNCTIONAL',
    ),
    HistoricalRecord(
      deskId: 'LAB6 - PC29',
      category: 'MONITOR',
      brand: 'ACER',
      mfgSerial: '253R17569',
      dntsSerial: 'L6-MR-29',
      dateAcquired: 'August 2, 2025',
      notes: 'FUNCTIONAL',
    ),
    HistoricalRecord(
      deskId: 'LAB6 - PC30',
      category: 'MONITOR',
      brand: 'ACER',
      mfgSerial: '253R17406',
      dntsSerial: 'L6-MR-30',
      dateAcquired: 'August 2, 2025',
      notes: 'FUNCTIONAL',
    ),
    HistoricalRecord(
      deskId: 'LAB6 - PC31',
      category: 'MONITOR',
      brand: 'ACER',
      mfgSerial: '252401956',
      dntsSerial: 'L6-MR-31',
      dateAcquired: 'August 2, 2025',
      notes: 'FUNCTIONAL',
    ),
    HistoricalRecord(
      deskId: 'LAB6 - PC32',
      category: 'MONITOR',
      brand: 'ACER',
      mfgSerial: '253R17533',
      dntsSerial: 'L6-MR-32',
      dateAcquired: 'August 2, 2025',
      notes: 'FUNCTIONAL',
    ),
    HistoricalRecord(
      deskId: 'LAB6 - PC33',
      category: 'MONITOR',
      brand: 'ACER',
      mfgSerial: '253R17567',
      dntsSerial: 'L6-MR-33',
      dateAcquired: 'August 2, 2025',
      notes: 'FUNCTIONAL',
    ),
    HistoricalRecord(
      deskId: 'LAB6 - PC34',
      category: 'MONITOR',
      brand: 'ACER',
      mfgSerial: '253Q02056',
      dntsSerial: 'L6-MR-34',
      dateAcquired: 'August 2, 2025',
      notes: 'FUNCTIONAL',
    ),
    HistoricalRecord(
      deskId: 'LAB6 - PC35',
      category: 'MONITOR',
      brand: 'ACER',
      mfgSerial: '253R17517',
      dntsSerial: 'L6-MR-35',
      dateAcquired: 'August 2, 2025',
      notes: 'FUNCTIONAL',
    ),
    HistoricalRecord(
      deskId: 'LAB6 - PC36',
      category: 'MONITOR',
      brand: 'ACER',
      mfgSerial: '253R17448',
      dntsSerial: 'L6-MR-36',
      dateAcquired: 'August 2, 2025',
      notes: 'FUNCTIONAL',
    ),
    HistoricalRecord(
      deskId: 'LAB6 - PC37',
      category: 'MONITOR',
      brand: 'ACER',
      mfgSerial: '252401282',
      dntsSerial: 'L6-MR-37',
      dateAcquired: 'August 2, 2025',
      notes: 'FUNCTIONAL',
    ),
    HistoricalRecord(
      deskId: 'LAB6 - PC38',
      category: 'MONITOR',
      brand: 'ACER',
      mfgSerial: '252401230',
      dntsSerial: 'L6-MR-38',
      dateAcquired: 'August 2, 2025',
      notes: 'FUNCTIONAL',
    ),
    HistoricalRecord(
      deskId: 'LAB6 - PC39',
      category: 'MONITOR',
      brand: 'ACER',
      mfgSerial: '252400397',
      dntsSerial: 'L6-MR-39',
      dateAcquired: 'August 2, 2025',
      notes: 'FUNCTIONAL',
    ),
    HistoricalRecord(
      deskId: 'LAB6 - PC40',
      category: 'MONITOR',
      brand: 'ACER',
      mfgSerial: '253R17605',
      dntsSerial: 'L6-MR-40',
      dateAcquired: 'August 2, 2025',
      notes: 'FUNCTIONAL',
    ),
    HistoricalRecord(
      deskId: 'LAB6 - PC41',
      category: 'MONITOR',
      brand: 'ACER',
      mfgSerial: '252400374',
      dntsSerial: 'L6-MR-41',
      dateAcquired: 'August 2, 2025',
      notes: 'FUNCTIONAL',
    ),
    HistoricalRecord(
      deskId: 'LAB6 - PC42',
      category: 'MONITOR',
      brand: 'SAMSUNG',
      mfgSerial: 'MRCQHYCDB00196M',
      dntsSerial: 'L6-MR-42',
      dateAcquired: 'MARCH 1, 2018',
      notes: 'EXIBIT ROOM - FUNCTIONAL',
    ),
    HistoricalRecord(
      deskId: 'LAB6 - PC43',
      category: 'MONITOR',
      brand: 'SAMSUNG',
      mfgSerial: 'MRCQHYCDA03451Y',
      dntsSerial: 'L6-MR-43',
      dateAcquired: 'MARCH 1, 2018',
      notes: 'EXIBIT ROOM - FUNCTIONAL',
    ),
    HistoricalRecord(
      deskId: 'LAB6 - PC44',
      category: 'MONITOR',
      brand: 'SAMSUNG',
      mfgSerial: 'MRCQHYCDA03141F',
      dntsSerial: 'L6-MR-44',
      dateAcquired: 'MARCH 1, 2018',
      notes: 'EXIBIT ROOM - FUNCTIONAL',
    ),
    HistoricalRecord(
      deskId: 'LAB6 - PC45',
      category: 'MONITOR',
      brand: 'SAMSUNG',
      mfgSerial: 'MRCQHYCDB00171R',
      dntsSerial: 'L6-MR-45',
      dateAcquired: 'MARCH 1, 2018',
      notes: 'EXIBIT ROOM - FUNCTIONAL',
    ),
    HistoricalRecord(
      deskId: 'LAB6 - PC46',
      category: 'MONITOR',
      brand: 'SAMSUNG',
      mfgSerial: 'MRCQHYCD901097Z',
      dntsSerial: 'L6-MR-46',
      dateAcquired: 'MARCH 1, 2018',
      notes: 'EXIBIT ROOM - FUNCTIONAL',
    ),
    HistoricalRecord(
      deskId: 'LAB6 - PC47',
      category: 'MONITOR',
      brand: 'SAMSUNG',
      mfgSerial: 'MRCQHYCDA03306T',
      dntsSerial: 'LAB5-MR-46',
      dateAcquired: 'MARCH 1, 2018',
      notes: 'ID PROCESSING / PIT-OS - FUNCTIONAL',
    ),
    HistoricalRecord(
      deskId: 'LAB6 - PC48',
      category: 'MONITOR',
      brand: 'SAMSUNG',
      mfgSerial: 'MRCQHYCDA03424F',
      dntsSerial: 'LAB 5-MR-31',
      dateAcquired: 'MARCH 1, 2018',
      notes: 'ACCOUNTING - FUNCTIONAL',
    ),
  ];
}
